### ISSUE TITLE
Plugin expansion to add factory method structure checks.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#102]
Expand the `buildSrc` plugin to verify certain commonalities to these factory methods:
 * `@CheckResult` on method
 * `@NonNull` on method (#20)
 * `@NonNull` on all parameters (#20)
 * `Action1` return types use a wildcard bound (`? super Integer`)
 * Second parameters which are a `Func1` use a wildcard for first parameterized type (`? super ViewEvent`)

**Comment by hzsweers** [comment]
Part of the way through implementing this, and just realized I should probably ask: Would this be part of the kotlin generation process or separate functionality? I think I know the answer, but just to be clear...

#### Option 1 - Kotlin Gen:

**Pros**:
- Easy to plug in to the current code, no refactoring for sources retrieval code necessary.

**Cons**:
- Would only run on kotlin generation

#### Option 2 - Separate plugin implementation

**Pros**:
- Focused purpose and separation makes it easy to iterate on these checks for the future without tying them to kotlin generation
- Depending on how fast it is, could add this as a preBuild task for more aggressive checking. Disablable via "noverify" param or something.

**Cons**:
- None, really. Just more work, but probably for the better.

**Comment by hzsweers** [comment]
I liked option 2, and went with that if you want to take a look before I PR: https://github.com/hzsweers/RxBinding/tree/z/structured_checks

**Comment by JakeWharton** [comment]
Option 2 is fine, although sharing code between the two plugins shouldn't be out of the question. I don't think it needs the option to disable, create a task called `validateBindings` (or something) and make the `check` task on the project depend on it.

**Comment by JakeWharton** [comment]
Looks like it already caught some missing things, too!
