### ISSUE TITLE
Restore null checks. Auto-generate null check unit tests.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#106]
The support annotations are too easily fooled. Let's restore all the null checking.

In addition, the build plugin should be augmented to generate unit tests for every method that has a `@NonNull` annotation where it verifies that passing `null` throws a `NullPointerException` with a message of `foo == null` where "foo" is replaced with the name of the argument.

**Comment by hzsweers** [comment]
Alternatively, the verification could verify that each function starts a call to `checkNotNull()` and has the appropriate message. Or both?

**Comment by JakeWharton** [comment]
Sure, that would work too.
