### ISSUE TITLE
Scroll views support

### ISSUE THREAD

**Issue by desseim** [JakeWharton/RxBinding#112]
I have a fork which implements scroll events for `ScrollView` and `HorizontalScrollView`.
Since it requires the use of subclasses of these (because there is no listener interface for scroll events in the system classes), it felt of limited use and I didn't think of integrating it upstream.

It is pretty convenient though, and as I was thinking of extracting it to its own project with a dependency on `RxBinding` (easier maintenance), I thought I'd check first if there would be any value in merging it here.

**Comment by JakeWharton** [comment]
There is [`OnScrollChangeListener`][1] in API 23 which we'll be adding support for. I don't think we can force people to create subclasses and I'm not inclined to ship subclasses in this library.

 [1]: https://developer.android.com/reference/android/view/View.OnScrollChangeListener.html

**Comment by JakeWharton** [comment]
Also if you want to ship a separate library I think that would be fine. Not sure you'd even need the dependency, but it'd be fine.

I've created #120 to track the listener version.

**Comment by desseim** [comment]
This is quite late of an answer but I wanted to thank you for answering and bring better closure to this ticket.
My fork was targeting pre-23 (and was created before actually), it also included bindings for [your ViewPagerIndicator library](https://github.com/JakeWharton/ViewPagerIndicator) widgets, but I completely agree the main RxBinding shouldn't be cluttered with all this so I finally extracted them in [two](https://github.com/desseim/rxbinding-viewpagerindicator) minimal [libraries](https://github.com/desseim/rxbinding-scroll).
They depend on the main RxBinding in order to reuse things like `MainThreadSubscription`.
They're of very restricted use and are definitely not bound to acquire much fame anyway, but in case they'd be a problem with it you could always let me know.
