### ISSUE TITLE
Reattach previous listener while observer has unsubscribed

### ISSUE THREAD

**Issue by xfumihiro** [JakeWharton/RxBinding#117]
It would be helpful to restore the bindings rather than just tossing them out.

**Comment by JakeWharton** [comment]
You can do this yourself by combining operators like `.publish().autoConnect()`.

Doing something like this in the library is a heavy and extremely wasteful operation in the common case which is where you actually do not want this behavior. Besides, just recreating the listener isn't that expensive of an operation. There are no plans to do this which is documented in the README.

**Comment by xfumihiro** [comment]
thanks for the tips! :+1:
