### ISSUE TITLE
RxTextView.textChangesWithBefore

### ISSUE THREAD

**Issue by wKovacs64** [JakeWharton/RxBinding#137]
New to RxJava and RxBinding, I started out by doing some user input validation previously implemented via `TextWatcher`. I realized while attempting to leverage the `filter` operator that the Observable returned from `RxTextView.textChanges` only emits the new text. Would it be beneficial to add a similar Observable that also emitted the before value (from [`TextWatcher#beforeTextChanged`](https://developer.android.com/reference/android/text/TextWatcher.html#beforeTextChanged%28java.lang.CharSequence,%20int,%20int,%20int%29))?

**Comment by JakeWharton** [comment]
Can you show an example of how you would use it?

**Comment by wKovacs64** [comment]
I was thinking something like:
```Java
RxTextView.textChangesWithBefore(textView)
        .filter(this::compareBeforeAndAfter)
        .subscribe(beforeAndAfterPair -> {
            // ...
        });
```
Just imagining `Pair` in the example here, haven't put much thought into the best way to represent the two values.

**Comment by JakeWharton** [comment]
Got it. Will look into adding.

**Comment by wKovacs64** [comment]
Cool, thanks for considering it.

**Comment by xfumihiro** [comment]
#145
@wKovacs64 I've added a test case to demonstrate the usage that you mentioned.
