### ISSUE TITLE
Support RxTextView.error and RxTextView.errorRes actions

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/RxBinding#141]
In my code, I actually do use an Observable to control the error on a text view and would seem to be a likely choice for others to want

**Comment by JakeWharton** [comment]
Should be easy. I'm traveling the next few days. Feel free to send a PR
with tests. Otherwise myself or someone will get around to it eventually.

**Comment by xfumihiro** [comment]
Done. #142
