### ISSUE TITLE
Inheritance vs. enums for event differentiation.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#178]
There's currently two patterns for events that have multiple "actions" associated with them (for lack of a better term):
- Subclass a common event type: `AbstractFooEvent` + `FirstFooEvent` + `SecondFooEvent`
- Put an enum on a single event type: `FooEvent` with `FooEvent.Kind` enum and property.

Which of these do we want to standardize on?

Subclassing feels gross since the more specific types do not add any more information to the event (note: counter example below) and add multiple types to the public API, but it also allows RxJava's filter+cast operator `ofType` to be used. Putting an inner-enum on a single event type keeps the public API small and we could change these to implement `Func1<EventType, Boolean>` for use as a `filter` (e.g., `.filter(FooEvent.Kind.FIRST)`).

**Comment by JakeWharton** [comment]
cc @loganj @dlew ... not sure who else might have opinions here

**Comment by JakeWharton** [comment]
Concrete example: `ViewGroup.changeEvents` which emits view attach/detach events.

**Comment by JakeWharton** [comment]
Interesting data point: `RxAdapterView.selectionEvents` which uses subclassing because `AdapterViewNothingSelectionEvent` has no metadata but `AdapterViewItemSelectionEvent` carries the ID, position, selected view, and the source view.

**Comment by dlew** [comment]
`ofType` is just a special case of `filter`. In other words, I think the two have the same value. Given that,  I'd rather go the enum route since that lowers API size.

In the case of `selectionEvents`, the returned object could be modified such that if the kind is `NOTHING_SELECTED` then the rest of the metadata is null.

**Comment by dlew** [comment]
Thinking further on selectionEvents - the way it's setup now requires you to cast before you can extract data from it. The enum method would mean you could start attempting to extract data that doesn't exist. Hmm.

**Comment by loganj** [comment]
+1 to enums since that will keep most of the API slim and it facilitates pattern matching in Java (via switch statements).

There is also the option of using both. Then you can always filter and match on the event type, but you only cast and deal with a subclass when there's extra information.

```java
class SelectionEvent
  enum Type {
    NOTHING_SELECTED,
    ITEM_SELECTED;
  }

  final Type type;
}

class ItemSelectedEvent extends SelectionEvent {
  final long itemId;

  ItemSelectedEvent(long itemId) {
    super(ITEM_SELECTED);
    this.itemId = itemId;
  }
}
```

**Comment by loganj** [comment]
Kotlin of course can use sealed classes and get the same benefits with even nicer sugar.

```kotlin
sealed class SelectionEvent {
  object NothingSelected : SelectionEvent()
  data class ItemSelected(val id: Int) : SelectionEvent()
}
```

**Comment by grodin** [comment]
This is basically exactly the problem that Algebraic Data Types solve, and the Kotlin example above is a fine example.

There is a boilerplate-heavy solution in Java, but I don't know if it's something to introduce in this library due to it not being very idiomatic Java.

The solution is to declare an abstract base class with a private constructor and then the only subclasses you ever allow are inner classes of the base class. This has the same effect as the sealed Kotlin classes.

You can then optionally add a visitor to provide a kind of pattern matching.

It's a pretty ugly solution from a maintenance point of view, but you can build an OK-ish API to use it.

I'm on my phone, so writing code is a pain, but I'll add an example if wanted tomorrow.

**Comment by JakeWharton** [comment]
That's very  close to what we have now, except with package-scoped
constructors on the abstract class and sibling final classes.

**Comment by hzsweers** [comment]
I'm in favor of the enum-based approach as well, seems like the cleanest approach.

**Comment by vanniktech** [comment]
I'm also for the enum-based approach.

If we wanted to not use enums we could also use ints and the \@IntDef annotation. Both are fine for me

**Comment by erickok** [comment]
While `.filter(FooEvent.Kind.FIRST)` looks nice enough, it would not allow different event kinds to have their own data fields, unless the double-up approach suggested by @loganj would be used. As already put forward as an example, `RxAdapterView.selectionEvents` has a selection event that carries an ID.

Another example is the `ViewPager.OnPageChangeListener`. The current `ViewPagerPageSelectedOnSubscribe` only propages page selected events (with an integer) but if we would support also, say, `onPageScrolled` this no longer can be contained in the same object.

**Comment by JakeWharton** [comment]
Leaning towards subclasses. Kotlin's `when` and RxJava's `ofType` being the primary motivators.

**Comment by loganj** [comment]
Hadn't even considered `ofType`. :shoot:

**Comment by loganj** [comment]
:shipit: #autocorrect

**Comment by hzsweers** [comment]
Yep that sounds good to me

**Comment by dlew** [comment]
I still stand by [my previous statement](https://github.com/JakeWharton/RxBinding/issues/178#issuecomment-150569500) which is that `ofType` isn't all that different from `filter`. But I don't have a strong feeling either way, I think it's more valuable to just make a choice and move on.

**Comment by JakeWharton** [comment]
I'm punting this to 2.0 as well, but I think I'm still leaning towards subclasses. They solve more cases elegantly than enums.

**Comment by JakeWharton** [comment]
Based on numbers we already favor subclasses based solely on when we need to provide different properties for events. There's actually only 4 enums left, so I'm just going to convert them.
