### ISSUE TITLE
Observable<Void> for instanceless events in Java, Observable<Unit> in Kotlin

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#180]

**Comment by valeriyo** [comment]
:+1:

**Comment by dlew** [comment]
Out of curiosity, what made you change your mind on this point?

**Comment by JakeWharton** [comment]
Hmm, I don't remember being explicitly in favor of Object! I've always
wanted Unit in Kotlin but never bothered to do the work. There's no type in
Java that has the semantics exactly what we want (Unit nails it), but Void
is closer than Object.

**Comment by dlew** [comment]
I remember the reason having something to do with casting not working, but maybe I'm just misremembering.
