### ISSUE TITLE
Preference Support Library Bindings

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#184]
- [ ] change
- [ ] click
- [ ] display dialog
- [ ] navigate to screen

**Comment by JakeWharton** [comment]
One could argue these aren't views or widgets...

**Comment by dlew** [comment]
Would this be better suited as part of https://github.com/f2prateek/rx-preferences?

**Comment by JakeWharton** [comment]
Maybe as a sibling module.

I haven't used the preference UI stuff in like 4 years, but from what I
remember it does all the actual data binding itself and you only take care
of the UI. So I don't think there'd actually be much (if any) crossover.

**Comment by hzsweers** [comment]
Agreed with jake, I think this belongs here since it's just UI handling and not actually interacting with `SharedPreferences` directly

**Comment by JakeWharton** [comment]
I've decided these aren't views and thus are out of scope.
