### ISSUE TITLE
Proposal: Palette support

### ISSUE THREAD

**Issue by hzsweers** [JakeWharton/RxBinding#188]
The basic API for palette looks like this:

```java
// Synchronous
Palette p = Palette.from(bitmap).generate();

 // Asynchronous
Palette.from(bitmap).generate(new PaletteAsyncListener() {
     public void onGenerated(Palette p) {
         // Use generated instance
     }
 });
```

While async is useful, would be nice to have a simple binding around it to pipe it into an rx stream.

```java
RxPalette.generate(bitmap).subscribe(palette -> {...})
RxPalette.generate(bitmap, numColors).subscribe(palette -> {...})
RxPalette.generate(builder).subscribe(palette -> {...})
```

Only issue I forsee is function names, which would clash with the existing ones in kotlin when added as function extensions (unless kotlin considers the return type as part of the method signature?). My proposal would be to call them `generateAsync`, since that would match the current API but have a different signature since it wouldn't take a listener.

**Comment by JakeWharton** [comment]
RxBinding is restricted to only view-related bindings. That is, elements which show up in UIs. The general rule is that they are in `android.view.*` or `android.widget.*` packages (or the associated support library versions of these).

This would be a good target for a focused standalone library.

**Comment by hzsweers** [comment]
Ah true, that makes sense. I'll write it as a standalone then

**Comment by hzsweers** [comment]
FWIW I've released this now: https://github.com/hzsweers/RxPalette
