### ISSUE TITLE
Normalize @NonNull / checkNotNull usage

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#20]
Figure out if we want actual non-null verification or just nullability annotations.

**Comment by dlew** [comment]
My vote is on checkNotNull because the annotations are non-binding.

**Comment by JakeWharton** [comment]
To play devil's advocate to that, annotations show in the IDE for consumers
of the library whereas checkNotNull does not.

**Comment by dlew** [comment]
![](http://cdn.meme.am/instances/250x250/61585443.jpg)

**Comment by lolkittens** [comment]
Both seems like a good solution.

**Comment by vanvlack** [comment]
Using both allows the consumer to easily seeing can something be null/non-null and enforces a semi-fail fast contract.

Note that modern IDEs can give warnings, but there are people in the world that use simple text editors.

```java
public @Nonnull String hello(@Nonnull String name) {
  return "hello " + Objects.requireNonNulll(name, "name == null");
}
```

Above assumes JDK7+ (or in the case of android, api 19+) and the use of the `java.util.Objects` handler for non-null, which throws an NPE on null.

**Comment by tilal6991** [comment]
Another positive for NotNull annotation is the support of null typing by the Kotlin compiler in the upcoming milestone.

**Comment by JakeWharton** [comment]
@vanvlack we have `Preconditions.checkNotNull` which is fairly standard in libraries.

My biggest problem with both is that it causes a ton of warnings in the library projects for "needlessly" checking a `@NonNull` value against null. It can be suppressed, and perhaps that's the cost we pay, but it's just annoying.

**Comment by grodin** [comment]
Another +1 for both. If only one, I'd prefer `checkNotNull` with it _required_ to be documented in the JavaDoc.

**Comment by vanvlack** [comment]
@JakeWharton Yea, I'm a fan of using what the standard JDK gives us. If it's there, why use/create our own just to do it.

The nice thing about `@Nonnull` annotations is it gives the caller/user a contract to follow. If I see a method signature that has these annotations (whether `@Nonnull` or `@Nullable`), I know with certainty how to handle the call or results of a call.

Of course, this all assumes the implementer is following the contract that it set upon itself, thus the fail-fast `requireNonNull` on passed variables and making sure return values are non-null, either by using some `Optional` mechanism or guaranteeing the existence of values upon object creation.

> My biggest problem with both is that it causes a ton of warnings in the library projects for "needlessly" checking a @NonNull value against null. It can be suppressed, and perhaps that's the cost we pay, but it's just annoying.

I wouldn't say they are `needless` checking. To me, moving the check to one spot (object creation or value setting) is easier than checking for `null` through-out my code all over.

**Comment by JakeWharton** [comment]
> The nice thing about `@Nonnull` annotations is it gives the caller/user a contract to follow. If I see a method signature that has these annotations (whether `@Nonnull` or `@Nullable`), I know with certainty how to handle the call or results of a call.

But the number of people reading the documentation that closely can be rounded down to zero. As far as I'm concerned the _only_ value of these annotations is making IntelliJ show warnings and static analysis tools like findbugs and error-prone fail your build when you pass an unexpected value.

![screen shot 2015-05-21 at 10 19 16 am](https://cloud.githubusercontent.com/assets/66577/7750547/de9cea66-ffa2-11e4-856a-a42d3cbbedce.png)

Of course, this only works when the nullability of the argument can be statically determined. Sometimes it's ambiguous leading you to unknowingly pass `null` to the method which leads me to my next point...

> I wouldn't say they are needless checking. To me, moving the check to one spot (object creation or value setting) is easier than checking for null through-out my code all over.

It's absolutely needless checking because of its redundancy, not its location. In fact, you mention this in your point above:

> this all assumes the implementer is following the contract that it set upon itself, thus the fail-fast `requireNonNull` on passed variables

IntelliJ flags the null check as redundant because of the annotation:

![screen shot 2015-05-21 at 10 13 55 am](https://cloud.githubusercontent.com/assets/66577/7750473/5d9c4074-ffa2-11e4-9012-35f17cb8d3c2.png)

This makes it annoying on the persons developing the library since they need to now suppress that warning to ensure the ambiguously `null` argument does not make it through for an ambiguous `NullPointerException` down the road rather than the eager one up front.

![screen shot 2015-05-21 at 10 23 39 am](https://cloud.githubusercontent.com/assets/66577/7750666/7c5c3644-ffa3-11e4-9f50-7cc50e49093e.png)

I'm not opposed to this as I said above. It's just an annoying burden pushed onto library implementations that want absolute guarantees.

**Comment by grodin** [comment]
Do you still get the warning when using `Preconditions.checkNotNull()`? I use both annotations and a null check with that method and hadn't noticed any warnings. It's possible I turned off that inspection at some point though.

I've just checked and IntelliJ (or Android Studio at least) doesn't even show the annotations in either the JavaDoc popup or the popup for the parameters method, the value of the annotations is much less than I'd thought it was.

I personally have found them slightly useful when writing code, as it at least gives me some instant statically checked feedback if I've accidentally passed `null` somewhere, but given that you only get the warning when the static checking can prove that you _have_ passed a null, it's not as useful as it could be.

So I don't really care that much about annotations. As long as it's documented rigorously in the JavaDoc that nulls are not accepted, and we fail fast on them, beyond that it's a vaguely-nice-to-have, but not essential.

Ultimately, it's a bit of a bike-sheddy issue, and we should probably just commit to _some choice_ fairly quickly and move on.

**Comment by artem-zinnatullin** [comment]
> IntelliJ flags the null check as redundant because of the annotation:
This makes it annoying on the persons developing the library since they need to now suppress that warning to ensure the ambiguously null argument does not make it through for an ambiguous NullPointerException down the road rather than the eager one up front.

IntelliJ flags only direct check of nullability, but it won't flag indirect check via method call:
![screen shot 2015-05-21 at 17 35 06](https://cloud.githubusercontent.com/assets/967132/7750942/c482b7cc-ffdf-11e4-891c-639d43df6f87.png)

We use both `@NonNull/@Nullable` and `checkNotNull()` in our library and we don't have problems with suppressing that warning, so I'd vote for both annotations and assertions: some-safety at compile time and safety at runtime.

Btw, I'm thinking about renaming `checkNotNull()` to `assertNotNull()` or `verifyNotNull()` in our code, because in fact, "check" should return `boolean`/etc, but not throw an exception (or I have wrong expectations). Agree/disagree?

**Comment by JakeWharton** [comment]
Yes, yes I'm glossing over that fact. My point still stands about the redundancy.

> Agree/disagree?

[Disagree][1]. Also, who cares ¯\\\_(ツ)_/¯.

 [1]: http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Preconditions.html#checkNotNull(T,%20java.lang.Object)

**Comment by FranciscoEstevez** [comment]
A vote for the redundant behaviour of annotations plus checker redundancy.

**Comment by artem-zinnatullin** [comment]
> [Disagree](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/base/Preconditions.html#checkNotNull(T,%20java.lang.Object)). Also, who cares ¯\_(ツ)_/¯.

Yeah, but Guava's design is sometimes questionable too :)

 I have last argument about profit from annotations: [Kotlin](http://blog.jetbrains.com/kotlin/2015/04/upcoming-change-more-null-safety-for-java/) and probably other languages.

TL;TR:

```java
// Java
class Hey {

  @Nullable String yo(@NonNull String whoCares) {
    if (whoCares.lenght() > 0) {
      return "yo, whoCares = " + whoCares;
    } else {
      return null;
    }
  }
}
```

```kotlin

// Kotlin
{
  Hey hey = Hey();

  hey.yo(nullableString); // won't compile!
  hey.yo(nullableString ?: "nobody"); // will compile.

  val yoResult : String  = hey.yo("me"); // won't compile!
  val yoResult : String? = hey.yo("J");  // will compile.
}
```

http://blog.jetbrains.com/kotlin/2015/04/upcoming-change-more-null-safety-for-java/
> The details are described in this [spec-document](https://github.com/JetBrains/kotlin/blob/types-from-annotations/spec-docs/flexible-java-types.md#enhancing-signatures-with-annotated-declarations), but the overall idea is as follows: whenever we encounter nullability annotations in Java, and they do not conflict with anything around them (like overridden declarations in supertypes), we use precise types.

Use the ~~Power~~ Both, Luke!

**Comment by JakeWharton** [comment]
Yes, we were always going to use annotations. The argument was more whether the redundant explicit checks were also necessary.

**Comment by vanvlack** [comment]
> As long as it's documented rigorously in the JavaDoc that nulls are not accepted, and we fail fast on them, beyond that it's a vaguely-nice-to-have, but not essential

Agree, documentation is still needed. I'm not advocating for one over the other, just stating my opinion that both can/do help.

Note that the default in IntelliJ is to display a warning on `null` setting to a `@Nonnull` parameter, but this can also be configured to be an error or ignored.

I believe as of now, the annotations by themselves are only useful for warnings when you have it setup in an IDE.  You could bring in something like the Checker Framework, which will analyze your code at compile time and determine what is breaking that nonnull contract.

As long as there is consistency, whether that be annotations, runtime checks, documentation or a combination of those, that is really what matters.

**Comment by JakeWharton** [comment]
:+1: :+1:

error-prone and findbugs also fail builds on violation of nullability annotation contracts. I'm a fan.

**Comment by vanvlack** [comment]
> I've just checked and IntelliJ (or Android Studio at least) doesn't even show the annotations in either the JavaDoc popup or the popup for the parameters method, the value of the annotations is much less than I'd thought it was.

I'm using IntelliJ 14 and I not only see `@Nonnull` annotations in javadoc, but generating javadoc also includes the annotations. Unsure what Android Studio is built on though. The only thing that is not included is actual javadoc comment related info.

![intellij-javadoc-popup](https://cloud.githubusercontent.com/assets/190584/7755522/3fc22056-ffba-11e4-80b5-8184a09cbb31.jpg)

![nonnull-code-popup](https://cloud.githubusercontent.com/assets/190584/7755523/3fc3a99e-ffba-11e4-9752-6575842ebed5.jpg)

![nonnull-javadoc-jdk8](https://cloud.githubusercontent.com/assets/190584/7755466/de32202a-ffb9-11e4-8b65-4334683d5014.jpg)

**Comment by JakeWharton** [comment]
Those are `@Documented` versions from (I'm guessing?) the Checker Framework. The platform annotations are not `@Documented` versions, sadly, so they won't show up.

**Comment by JakeWharton** [comment]
http://r.android.com/151379

**Comment by vanvlack** [comment]
@JakeWharton likely due to me using:

```xml
<groupId>com.google.code.findbugs</groupId>
<artifactId>jsr305</artifactId>
```

Which seems to have `@Documented` annotations.

**Comment by vanvlack** [comment]
@JakeWharton another option, is to only annotate those parameters that are `Nullable` in your code. You can then state that all parameters are expected to be `Nonnull`, unless otherwise noted.

You should then only need to check for `null` on methods, vs doing explicit `Nonnull` annotations.

Just a thought.

**Comment by JakeWharton** [comment]
That seems the least best option in terms of utility to the consumer of the
library. The IDE won't warn when they pass null to a non-Nullable-annotated
parameter nor will the library fail that value eagerly.
