### ISSUE TITLE
Cannot setError when using RxTextView.textChanges

### ISSUE THREAD

**Issue by ainesophaur** [JakeWharton/RxBinding#201]
It seems like same error as #192 but under different circumstances.

I'm not sure if I'm thinking about this in the wrong manner. I'm observing an edit text using `RxTextView.textChanges` and I use `setError()` to provide an error field. I understand the reasoning of why I'm getting the IndexOutOfBoundsException as the setError is "changing the text", but I'm curious if there is any workarounds suggested.

```java
RxTextView.textChanges(priceIncreaseEditText)
  .debounce(200, TimeUnit.MILLISECONDS)
  .filter(s -> !(TextUtils.isEmpty(s)))
  .subscribe(strVal -> {
     priceIncreaseEditText.setError("Some error text");
   });
```

Produces the error

```
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at android.widget.TextView.sendOnTextChanged(TextView.java:8969)
            at android.widget.TextView.handleTextChanged(TextView.java:9066)
            at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:11641)
            at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:968)
```

**Comment by JakeWharton** [comment]
I cannot reproduce. Can you provide a tiny sample?

You have at least one bug, though, you cannot touch the UI from a thread other than the main thread. Your `debounce` should look like this:
```java
RxTextView.textChanges(priceIncreaseEditText)
  .debounce(200, TimeUnit.MILLISECONDS, AndroidSchedulers.mainThread())
  .filter(s -> !(TextUtils.isEmpty(s)))
  .subscribe(strVal -> {
     priceIncreaseEditText.setError("Some error text");
   });
```

**Comment by JakeWharton** [comment]
Also,

> setError is "changing the text"

This is not true. Error text does not trigger a text change event.

**Comment by ainesophaur** [comment]
I cannot seem to reproduce the issue in a new project. It seems to be something specific to my build. I was using observeOn to use the main thread, but glad to know I can put it in the debouce directly.

This can be closed out. Thanks for replying!
