### ISSUE TITLE
textchange invoke during oncreate

### ISSUE THREAD

**Issue by shingkit** [JakeWharton/RxBinding#203]
Hi,JakeWharton,Thanks for the great job,I'm studying RxBinding recently,and I have a confuse.When i write the code in activity's onCreate() method,the toast invoked every time i open the activity,is there some NOT TODO?
```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_rx_binding);
        ButterKnife.bind(this); 

        RxTextView.textChanges(tvBinding).subscribe((event) -> {
            Toast.makeText(RxBindingActivity.this, "文字变了，我也变！", Toast.LENGTH_SHORT).show();
        });
    }
```

**Comment by erickok** [comment]
Duplicate of #61. You can use `.skip(1)` if you don't want the initial emitted value.

**Comment by shingkit** [comment]
@erickok Thanks
