### ISSUE TITLE
Documentation issue: share() is not what people should use for statefull events

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/RxBinding#207]
The readme says "Multiple listeners to the same view events can be achieved through share()." That is going to be bad advice in many cases and will cause bugs that most people are going to have trouble figuring out (I've spent several hours myself trying to figure out how to solve this).

The problem is with the initial value emitted from the Observable. When you have an Observable shared with share() that emits an initial value, only the first one to subscribe to the shared observable will cause the OnSubscribe code to be run and thus that first subscriber will be the only one to receive the initial value. Later subscribers will not get an initial value.

For events like button clicks this is not an issue since there is no initial value, but for things like the content of a text field or whether a check box is checked it is almost certainly not what you want.

For these types of events where there is an initial value, the correct solution is to use `replay(1).refCount()` instead of `share()`. The readme should probably discuss this so it isn't encouraging people to do the wrong thing.

**Comment by eleventigers** [comment]
@dalewking wouldn't `ConnectableObservable` from `publish()` be more appropriate in this situation?

**Comment by JakeWharton** [comment]
Yep. That's what we use everywhere!

**Comment by dalewking** [comment]
ConnectableObservable is another way to go and was my first attempt but was much more complex. The connect call itself returns a separate subscription that has to be managed.

I am fine with mentioning it as another alternative but the point is that the documentation should not just say to use share() since it is not appropriate for statefull events and will cause problems with novice users.

**Comment by JakeWharton** [comment]
Mentioned all three in 0929dacba4e003f76cb7c02d03d28f6dd269b5a7
