### ISSUE TITLE
Allow "un-selection" of a RadioGroup button?

### ISSUE THREAD

**Issue by kaushikgopal** [JakeWharton/RxBinding#217]
The [`distinctUntilChanged` qualifier helps filter out clicks on the same radio button choice](https://github.com/JakeWharton/RxBinding/blob/1567939c6467482de3977ad54dc3e88ba33c1f5c/rxbinding/src/main/java/com/jakewharton/rxbinding/widget/RxRadioGroup.java#L24), however I have a use case where I would like to know of _all_ events emitted. I would like to "unset" the radio group (by `.clear`ing the Radio Group) if a user clicks on the same radio button choice twice.

Is this too specific for `RxBindings`? Potential method signatures (if issue is worth considering):

1. `Observable<Integer> checkedAllChanges(RadioGroup view)`
2. `Observable<Integer> checkedEvents(RadioGroup view)`
3. `Observable<Integer> checkedChangesAll(RadioGroup view)`

**Comment by JakeWharton** [comment]
The reason this was initially added was that RadioGroup re-fired selected IDs when actually clearing the selection. So I'd be curious to see if you could even get something like that working.

In general I'm in favor of as closely mapping to listeners as possible and leaving the higher-level composition to application code. In this place we deviated because it seemed like a clear bug (and I believe there is a bug tracking it) that made the current behavior almost useless. I'm not opposed to reverting it if it can be proved to be useful without.

**Comment by dlew** [comment]
Is it that the RadioGroup fires twice in quick succession when clearing (the first of which is a repeat)? In that case you could add a debounce so that only the last change gets emitted.

**Comment by JakeWharton** [comment]
I don't remember exactly. The commit message says as much though: https://github.com/JakeWharton/RxBinding/commit/b4780baef00531325b28825a632574982c6b3b2d

I'll try to write a test case for it so we have something to build on.

**Comment by JakeWharton** [comment]
Even with `distinctUntilChanged` removed, events are not fired for subsequent clicks on a checked ID.

This test passes (with the operator removed):
```java
RecordingObserver<Integer> o = new RecordingObserver<>();
Subscription subscription = RxRadioGroup.checkedChanges(view).subscribe(o);
assertThat(o.takeNext()).isEqualTo(-1);
o.assertNoMoreEvents();

view.check(1);
assertThat(o.takeNext()).isEqualTo(1);
assertThat(o.takeNext()).isEqualTo(1); // LOL
o.assertNoMoreEvents();

view.check(1);
o.assertNoMoreEvents();

view.clearCheck();
assertThat(o.takeNext()).isEqualTo(1); // LOLOL
assertThat(o.takeNext()).isEqualTo(-1);
o.assertNoMoreEvents();

view.check(2);
assertThat(o.takeNext()).isEqualTo(2);
assertThat(o.takeNext()).isEqualTo(2); // LOL
o.assertNoMoreEvents();

subscription.unsubscribe();

view.check(1);
o.assertNoMoreEvents();
```

**Comment by kaushikgopal** [comment]
Wow (the result of) multiple parts of that test don't make sense to me :S

```
view.check(1);
assertThat(o.takeNext()).isEqualTo(1);
assertThat(o.takeNext()).isEqualTo(1); // LOL
o.assertNoMoreEvents();

view.check(1);
o.assertNoMoreEvents();
```
^ ... arr

```
view.clearCheck();
assertThat(o.takeNext()).isEqualTo(1); // LOLOL
assertThat(o.takeNext()).isEqualTo(-1);
```
^ arr.... ?

is that a reliable firing of sequence ? so if we were to call `.clearCheck` again, is the expectation this:

```
assertThat(o.takeNext()).isEqualTo(1);
assertThat(o.takeNext()).isEqualTo(-1);
```

will also try to make sense of the events being fired.

**Comment by JakeWharton** [comment]
Calling `clearCheck` twice should emit nothing the second time.

**Comment by JakeWharton** [comment]
Closing as I don't think there's any action to take here. Happy to discuss otherwise.

**Comment by kaushikgopal** [comment]
:+1: apologies, should have closed it earlier.
