### ISSUE TITLE
Need new release for Kotlin 1.0 RC

### ISSUE THREAD

**Issue by dalewking** [JakeWharton/RxBinding#226]
Apparently JetBrains broke binary compatibility again and the latest build cannot be used in latest Kotlin

**Comment by JakeWharton** [comment]
The RC was merged in by #225 so the latest SNAPSHOT should work, or JitPack can be used as an immediate solution for a stable artifact. There's unlikely to be a release for at least a week, as I have higher priorities.

**Comment by JakeWharton** [comment]
0.4.0 released
