### ISSUE TITLE
TextViewAfterTextChangeEvent has @NonNull annotation

### ISSUE THREAD

**Issue by trevorrjohn** [JakeWharton/RxBinding#230]
This might just be a weird edge case, or it might be an implementation detail of RecordingObserver that I don't know about. But looking at [`TextViewAfterTextChangeEvent#editable()`](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewAfterTextChangeEvent.java#L30) it annotated with `@NonNull`. But then when I look at the [test for it](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/androidTest/java/com/jakewharton/rxbinding/widget/RxTextViewTest.java#L165),  it is actually asserting a `null` value. 

I just wanted to clarify the correct behavior here. I don't believe the `TextWatcher#afterTextChanged` ever fires with a `null` editable, but I still think either the test should be updated to reflect this or the annotation should be removed... 

Thoughts?

**Comment by JakeWharton** [comment]
It's nullable.
