### ISSUE TITLE
RxAdapterView.itemSelections(adapter) should emit both position and id

### ISSUE THREAD

**Issue by ena1106** [JakeWharton/RxBinding#233]
I think it would be useful if the `RxAdapterView.itemSelections(adapter)` emits both position and id of selected item.
I'm using hasStableIds true in my adapter and the fact that the observable emits only the position prevents me from using it. It should emit events of something like `android.util.Pair<Integer,Long>` or a custom wrapper.

**Comment by egor-n** [comment]
You should be able to map index to a `Pair<Integer, Long>` using [getItemIdAtPosition](http://developer.android.com/reference/android/widget/AdapterView.html#getItemIdAtPosition(int)).

**Comment by ena1106** [comment]
You are right, thank you.
