### ISSUE TITLE
How to import RxBinding projects as source code? 

### ISSUE THREAD

**Issue by DavidMihola** [JakeWharton/RxBinding#234]
I am trying to import `RxBinding/rxbinding` into one of my projects *as source code*. So, currently my setup looks like this:

```
~/AndroidStudioProjects
+-- RxBinding
+-- MyRxBindingTestProject
```
where RxBinding contains a clone of the github repository and MyRxBindingTestProject is the project where I want to import the code using the following `settings.gradle`:

```
include ':app'
include ':rxbinding'
project(':rxbinding').projectDir = new File('../RxBinding/rxbinding')
```

This, however, does not work, because:
```
Error:(3, 0) Cannot get property 'androidPlugin' on extra properties extension as it does not exist
```

I *could* get it to work by defining all the `ext` variables in my own top-level `build.gradle` but then I would be imposing library versions on RxBinding or at least would have to check if I am using compatible version numbers.

Is that just something that one has to live with using these centralized version definitions or am I maybe importing RxBinding in a wrong way?

(I have to confess that I am also asking this because I ran into the same problem in my own library where I was trying to copy approach taken here. See [my Stackoverflow question.](http://stackoverflow.com/questions/35794921/rootproject-in-a-gradle-module-thats-imported-to-another-project/35884556)).

Thank for any comments!

**Comment by hzsweers** [comment]
I think this question is best suited to stackoverflow. It's a gradle question, not really RxBinding. To answer your question though, the project has all dependency references centralized in `dependencies.gradle` and adds them to the project extensions. If you don't want to set that up in your project, you'll need to manually specify all the dependencies in your RxBinding module clone.

**Comment by DavidMihola** [comment]
>  the project has all dependency references centralized in dependencies.gradle and adds them to the project extensions.

Yes, of course! But the problem seems to be that when used in the context of another top-level project these project extensions are not available anymore because the `rootProject` (for example in `rxbinding/build.gradle`) now points to the project defined in the top-level `build.gradle` of the new project. And not anymore to the RxBinding top-level `build.gradle` which contains the project extensions.

Or are you saying I should copy the `dependencies.gradle` to my project and import them into the top-level `build.gradle` of the project that uses RxBinding?

I apologize for asking a semi-off-topic question here. Unfortunately, the only reply I received on Stackoverflow was more of workaround and not the real solution - if any even exists. And since I suppose there must be some way to properly import RxBinding as a source project I was hoping this would be a good place to ask. Or is that just something you would never do - should I simply deploy RxBinding locally and then add it as a normal dependency?

**Comment by hzsweers** [comment]
Either copy them in yourself, or update the dependencies in your cloned copy to be explicit/not use project extensions since they won't exist in your project.

Your followup kind of gets to a meta question: why are you doing any of this? Why can you not just add it as a normal dependency? If deploying locally and adding as a normal dependency is acceptable, why can't you just use it as a dependency from mavencentral?

**Comment by DavidMihola** [comment]
> Why are you doing any of this? Why can you not just add it as a normal dependency?

I was trying to get it set up so that I could play around with the RxBinding source code and try the changes in an Android project.

> If deploying locally and adding as a normal dependency is acceptable,

Of course, deploying the snapshot locally after any changes is a possibility but it is clearly inferior to just hitting Run in the test project. Therefore, I would prefer importing the project as source.

I thought that there should be a way to do that which:
* does not require any changes in the gradle setup of RxBinding
* does not require me to add any info in my test project just for the sake of the RxBinding modules.

I just didn't want to use a "wrong" solution. But if there is no better one, that's fine, too.

In any case, thank you very much for your patience and for your comments!

**Comment by hzsweers** [comment]
You'll have to deal with it. It's Jake's project and as the owner he gets to structure it the way he wants. The solutions I suggested are trivial changes to get yours up and running, it's not difficult.

Anywhere you see something like `rootProject.ext. androidPlugin`, replace it with the explicit dependency (e.g. `'com.android.tools.build:gradle:2.0.0-beta6'`)

**Comment by DavidMihola** [comment]
Oh, I am sorry - I didn't even remotely mean it that way! I have nothing but the greatest respect for Jake's work and I think if anyone would get the setup of a complex project right, it'd be him.

On the contrary, I was supposing that the way I was importing the project must be faulty in some way - and I simply wanted to learn how you guys would to it.

As I wrote in my initial question, I know what I need to do in my test project to make it work. If that's what I need to do to handle these situations - fine! I just didn't want to miss a better solution.

**Comment by JakeWharton** [comment]
Don't use this project's build file, create your own which points at the clone's sources and includes the required dependencies itself.

`RxBinding/build.gradle`:
```groovy
apply plugin: 'android'

android {
  sourceSets {
    main.java.srcDirs = 'clone/rxbinding/src/main/java'
  }
}

dependencies {
  // ...
}
```

**Comment by DavidMihola** [comment]
@JakeWharton: Thanks a lot for the explanation!
