### ISSUE TITLE
Support libraries version update?

### ISSUE THREAD

**Issue by piatt** [JakeWharton/RxBinding#239]
In dependencies.gradle, the version referenced for all support libraries is 23.1.0, a relatively older release. Since then, there have been lots of updates and fixes. Current version is 23.2.1. Are there plans to update these? The changes that apply most to my usage are related to RecyclerView's measurement changes to support wrap_content. If I compile a newer version of an android support library in my own gradle project, will RxBinding respect that version or use the one defined in dependencies.gradle?

**Comment by JakeWharton** [comment]
You can declare the newer version in your `build.gradle` and those versions will be used for building your app. Confirm by running `./gradlew dependencies`.

The only reason to bump in this project is if there's new APIs that need binding against. We won't be making releases to track every support library update though.

> a relatively older release

This is literally the previous release. It's not _that_ old.

**Comment by piatt** [comment]
Thanks for the super quick reply!
