### ISSUE TITLE
RxTabLayout cancelling ViewPager setup

### ISSUE THREAD

**Issue by Ribesg** [JakeWharton/RxBinding#242]
Basically, when in the setup of a `TabLayout`, you do this:
````
setupWithViewPager(viewPager)
val selectionEventObs = selectionEvents()
````
This effectively break the `TabLayout` <=> `ViewPager` setup

My idea is that `selectionEvents()` should either check that there is an existing listener and wrap it, or at least take a boolean parameter to choose to wrap it.

**Comment by JakeWharton** [comment]
There is no getter for the listener so neither option is viable. Listen to
selection events on the ViewPager instead.

**Comment by Ribesg** [comment]
I'm trying to implement a dead simple / extremely common use case and it's simply impossible currently.

I want to be able to
1. Have a `TabLayout` setup with a `ViewPager` with `TabLayout.setupViewPager`
2. Listen to `TabLayout`'s `RESELECTED` events to scroll the `ViewPager`'s content to the top

What do you think of making some tool for TabLayouts associated to ViewPagers? Like some kind of `RxTabLayoutViewPager.setup(TabLayout, ViewPager)` which could return some object on which you could call functions like `tabSelectionEvents` _and_ `pageSelectionEvents`.

For now I have to rely on not using Rx at all here I guess.

**Comment by Ribesg** [comment]
Here is the solution I implemented, hope it'll help.
````kotlin
object RxTabLayoutViewPager {

    fun setup(tabLayout: TabLayout, viewPager: ViewPager): Observable<TabLayoutSelectionEvent> {
        if (!isMainThread()) throw IllegalStateException("Should be running on main thread")
        tabLayout.setupWithViewPager(viewPager)
        return Observable.create<TabLayoutSelectionEvent> { sub ->
            val listener = object : ViewPagerOnTabSelectedListener(viewPager) {

                override fun onTabReselected(tab: Tab) {
                    super.onTabReselected(tab)
                    sub.onNext(TabLayoutSelectionEvent.create(tabLayout, Kind.RESELECTED, tab))
                }

                override fun onTabSelected(tab: Tab) {
                    super.onTabSelected(tab)
                    sub.onNext(TabLayoutSelectionEvent.create(tabLayout, Kind.SELECTED, tab))
                }

                override fun onTabUnselected(tab: Tab) {
                    super.onTabUnselected(tab)
                    sub.onNext(TabLayoutSelectionEvent.create(tabLayout, Kind.UNSELECTED, tab))
                }

            }
            tabLayout.setOnTabSelectedListener(listener)
            sub.add(object : MainThreadSubscription() {

                override fun onUnsubscribe() {
                    tabLayout.setOnTabSelectedListener(ViewPagerOnTabSelectedListener(viewPager))
                }

            })
        }
    }

}

````

**Comment by JakeWharton** [comment]
That seems reasonable, but not something I want to include in the library because while it's a common interaction between to UI components, it's far too specific and I don't want to have to deal with other combinations forever.
