### ISSUE TITLE
Some question about useing ...

### ISSUE THREAD

**Issue by Samsu7609** [JakeWharton/RxBinding#244]
Hello all i'm trying learning useing RxBinding

 Observable<Boolean> checkEmail = RxTextView.textChangeEvents(emailEdit)
                .map(new Func1<TextViewTextChangeEvent, Boolean>() {
                    @Override
                    public Boolean call(TextViewTextChangeEvent textViewTextChangeEvent) {
                        boolean isEmpty = TextUtils.isEmpty(textViewTextChangeEvent.text().toString());
                        return !isEmpty;
                    }
                });

how can i Unsubscribe at Activity onDestory()

Sorry for my pool english... thanks all ^^

**Comment by smer4ik** [comment]
I think you want something like this:
```java
Observable<Boolean> checkEmail = RxTextView.textChangeEvents(editText)
            .map(new Func1<TextViewTextChangeEvent, Boolean>() {
                @Override
                public Boolean call(TextViewTextChangeEvent textViewTextChangeEvent) {
                    boolean isEmpty = TextUtils.isEmpty(textViewTextChangeEvent.text().toString());
                    return !isEmpty;
                }
            });

    Subscription subscription = checkEmail.subscribe(bool -> {
        // do some staff here
    });

    @Override
    public void onDestroy() {
        super.onDestroy();
        subscription.unsubscribe();
    }
```

**Comment by Samsu7609** [comment]
@smer4ik thanks your answer
if  i not do 
Subscription subscription = checkEmail.subscribe(....)  subscription.unsubscribe();
app will cause memory leak ?

^^

**Comment by JakeWharton** [comment]
Your best bet is to put the `Subscription` in a field or add it to a `CompositionSubscription` field which you then unsubscribe in onDestroy.

There's some tips here: https://www.youtube.com/watch?v=QdmkXL7XikQ

Since this is a general RxJava usage question and not RxBinding specific, I would recommend using StackOverflow with the rx-java and rx-android tags and/or using the RxJava mailing list.
