### ISSUE TITLE
Emitting first event always "" empty String  

### ISSUE THREAD

**Issue by jemshit** [JakeWharton/RxBinding#247]
I'm using  `RxSearchView.queryTextChangeEvents()`and when i create `Activity`, it emits "" empty String  even there is no search query made, and `SearchView` is collapsed, not even open.
The old code is this and it doesn't call `onQueryTextChange` until i click and open `SearchView`

``` java
 searchView.setOnQueryTextListener(new SearchView.OnQueryTextListener() {
                @Override
                public boolean onQueryTextSubmit(String query) {
                    Toast.makeText(getActivity(), "SearchOnQueryTextSubmit: " + query, Toast.LENGTH_SHORT).show();
                    searchItem.collapseActionView();
                    return false;
                }
                @Override
                public boolean onQueryTextChange(String s) {
                    Toast.makeText(getActivity(), "SearchOnQueryChanged: " + s, Toast.LENGTH_SHORT).show();
                    return false;
                }
            });
```

Rx code is below and it emits `searchViewQueryTextEvent` event when i create `Activity`, **also** when i click search icon, both "" empty

``` java
RxSearchView.queryTextChangeEvents(searchView)
                    .doOnNext((searchViewQueryTextEvent)->{
                        if (searchViewQueryTextEvent.isSubmitted()) {
                            searchItem.collapseActionView();
                        }
                    })
                    .debounce(750, TimeUnit.MILLISECONDS)
                    .observeOn(AndroidSchedulers.mainThread())
                    .subscribe(searchViewQueryTextEvent -> {
                        Log.d("test", "query: " + searchViewQueryTextEvent.queryText());

                    });
```

Is this normal ? Should i **always** skip first event for above and `textChanges()`, since they all seems to emit "" as first item ?

**Comment by erickok** [comment]
Yes, this is by design. See SearchViewQueryTextChangeEventsOnSubscribe.java#L47

**Comment by jemshit** [comment]
`textChanges()` emits when you click `EditText`, but `.queryTextChangeEvents()` emits **before** you click, also after you click `SearchView` icon. What is the purpose ?

**Comment by JakeWharton** [comment]
See #356 and #153.
