### ISSUE TITLE
RxImageView.imageChanges() 

### ISSUE THREAD

**Issue by lawloretienne** [JakeWharton/RxBinding#249]
Similar to how you can create an `Observable` when an `EditText` changes `RxTextView.textChanges(editText)` can you create an `Observable` when an `ImageView` `src` attribute changes ?

**Comment by artem-zinnatullin** [comment]
As far as I know, `ImageView` has no public api to listen to `src` changes, you can create custom `ImageView` with such api and provide Rx binding for it.

**Comment by lawloretienne** [comment]
@artem-zinnatullin Do you have any example of providing RxBinding to a custom View?

**Comment by artem-zinnatullin** [comment]
This repo has tons of examples for all kinds of views :)

**Comment by JakeWharton** [comment]
There is no listener for this so we cannot support it.

**Comment by lawloretienne** [comment]
I figured out how to pull this off.
https://gist.github.com/lawloretienne/ba02c79e4a8829d88f54f5739c6036b1
