### ISSUE TITLE
An observable combining all TextView changes as one stream, with a single TextWatcher instance?

### ISSUE THREAD

**Issue by K4KYA** [JakeWharton/RxBinding#252]
First off - big fan of this repo, massive thanks to everyone who's contributed so far!

I noticed something that caught my eye when digging through the code. At the moment if I want to subscribe to > 1 of the events that wrap `TextWatcher` callbacks (i.e. textChangeEvents, beforeTextChangeEvents, afterTextChangeEvents), each new subscription allocates a new `TextWatcher` object. 

Would we be able to implement a single `textEvents()` method which would emit all `TextWatcher` events in a single stream, with only 1 `TextWatcher` object allocated, which we could filter through for events of interest?

e.g. usage:
```
rxTextView.textEvents()
    .filter( e -> e instanceOf TextViewAfterChangeEvent || e instanceOf TextViewBeforeTextChangeEvent )
    .subscribe(
        // Do something with events
    );
```

I realise something similar is possible by subscribing and merging the streams of interest, so I'm open for discussion as to whether or not this is a good or bad idea, willing to contribute if good.

**Comment by JakeWharton** [comment]
I'm not sure how common this is. How many times are you doing this in your app? The multiple `TextWatcher` allocations are going to be very small and you would need to be doing this on hundreds of `TextView`s simultaneously to notice any measurable impact on your app.

**Comment by K4KYA** [comment]
Agree, it's not a particularly common use case. Merging the subscriptions for each event of interest is probably the way to go here then?

**Comment by K4KYA** [comment]
Given the previous comment, I'm closing this issue. The performance gains would be negligible and which is obviously enough to constitute a new binding. Alternative implementations using merges on other events are a trivial alternative.
