### ISSUE TITLE
Show progressbar as retrofit fetches data asynchronously

### ISSUE THREAD

**Issue by jpaseneta** [JakeWharton/RxBinding#253]
Hi @JakeWharton 

I have this code snippet:
`Button b = (Button)layout.findViewById(R.id.fetchbutton);
        RxView.clicks(b).subscribe( obj -> apiService.getUser(10).subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(user -> postGetUser(user), throwable -> throwable.printStackTrace()));`
postGetUser(user) simply notifies my recyclerview of the new items to be added.

I have been wondering if it is possible somewhere with the syntax to show a progress bar as soon as a rest api call by retrofit is executed then hide it after getting data?

Thank you.

**Comment by JakeWharton** [comment]
You can use `doOnNext` to show it after `clicks` and then `doOnNext` to hide it after `observeOn`.

Please use the RxJava mailing list or StackOverflow for general usage questions. This isn't really an RxBindings question.
