### ISSUE TITLE
Remove RxJava from plugin. Use Kotlin's stdlib.

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#258]

**Comment by JakeWharton** [comment]
Follow-up from #251.

**Comment by grodin** [comment]
I've essentially done the work for this, but there don't seem to be any unit tests for the plugin, so I'm not sure how to test that I haven't broken something. Is adding tests for `ValidateBindingsTask` out of scope for this, or can I just go ahead and do so? I'd rather ask before submitting a PR which does too much.

**Comment by JakeWharton** [comment]
You can just run the `generateKotlin` task and ensure that none of the code
in the kotlin modules have changed. The CI build will verify this as well,
so just sending the PR would be fine.
