### ISSUE TITLE
Invalid Path

### ISSUE THREAD

**Issue by Wy-Nasty** [JakeWharton/RxBinding#260]
When trying to pull down the library via maven there are dependency issues. I excluded the annotations dependency since the maven link is dead. The rxandroid dependency under rxbinding doesn't work. States that there is a "broken path." Any thoughts on this?

**Comment by JakeWharton** [comment]
Can you provide more information? As far as I can tell this is a build system issue and not an issue with the library.

**Comment by Wy-Nasty** [comment]
I can try. I add in the maven dependency in my project pom

<dependency>
    <groupId>com.jakewharton.rxbinding</groupId>
    <artifactId>rxbinding</artifactId>
    <version>0.4.0</version>
</dependency>

Then when I go to refresh/download all of my project dependencies it fails to download two dependencies. Them being

io.reactivex:rxandroid:1.1.0
com.android.support:support-annotations:23.1.0

the second one isn't available in maven so that's not surprising. But the first one should be available. Also, there isn't any issue downloading the rxjava dependency.

**Comment by JakeWharton** [comment]
Hmm it sounds like a bug in the android-maven-plugin. (You are using the android-maven plugin, right?) It should be able to handle aar dependencies (including their transitive dependencies) just fine.

**Comment by Wy-Nasty** [comment]
Yeah, I am using the android-maven-plugin. Must be something specific to my build environment since I would think others would see this as well. I guess this can get closed. I'll have to figure out whats wrong. Odd that it does resolve one of the dependencies though. Thank you.

**Comment by JakeWharton** [comment]
Actually I'm just willing to bet everyone else is using Gradle at this
point so it's unlikely that many aars with dependencies are being consumed
by Maven.

**Comment by Wy-Nasty** [comment]
Yeah that makes sense. Well, I think I got it to work. Had to explcitly define all dependencies and types. Kind of wonky, but hey, if it works. Thank you sir
