### ISSUE TITLE
OnError while emitting onNext value: retrofit2.Response.class

### ISSUE THREAD

**Issue by fahimsakri** [JakeWharton/RxBinding#271]
<img width="947" alt="screen shot 2016-07-24 at 7 38 50 am" src="https://cloud.githubusercontent.com/assets/4579397/17081345/e9edc42c-5171-11e6-83c5-b7437f31a131.png">

**Comment by JakeWharton** [comment]
This is not an error with this library. Your `doOnEach` function is throwing an exception.

**Comment by fahimsakri** [comment]
I have not used doOnEach method in my code..

Used code in my app is 

 Subscription subscription = requestObservable
                //.subscribeOn(Schedulers.io())
                .subscribeOn(Schedulers.newThread())
                .observeOn(AndroidSchedulers.mainThread())
                .retryWhen(new RetryWithConnectivityIncremental(fromFragment, parentActivity, requestCode))
                .doOnError(s -> callOnError(requestCode, s, fromFragment))
                .onErrorResumeNext(Observable.empty())
                .unsubscribeOn(Schedulers.io())
                .doOnNext(s -> callOnSuccess(requestCode, s, fromFragment))
                .subscribe();

**Comment by JakeWharton** [comment]
The stacktrace indicates it's your doOnNext.
