### ISSUE TITLE
Observable.create() vs Observable.fromAsync()

### ISSUE THREAD

**Issue by alex-townsend** [JakeWharton/RxBinding#274]
RxJava 1.1.7 introduced `Observable.fromAsync()` to "... bridge the callback world with the reactive". Would implementing `Observable.fromAsync()` with the callback-based view listeners in Android be functionally the same as the `Observable.create()` with `Observable.OnSubscribe<T>` method that RxBinding uses?

Example `Observable.fromAsync()` vs [TextViewTextOnSubscribe](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/widget/TextViewTextOnSubscribe.java)

```
public static Observable<CharSequence> textChanges(final TextView textView) {
        return Observable.fromAsync(new Action1<AsyncEmitter<CharSequence>>() {
            @Override
            public void call(final AsyncEmitter<CharSequence> emitter) {
                final TextWatcher textWatcher = new SimpleTextWatcher() {
                    @Override
                    public void afterTextChanged(Editable s) {
                        emitter.onNext(s);
                    }
                };
                textView.addTextChangedListener(textWatcher);
                
                final AsyncEmitter.Cancellable cancellable = new AsyncEmitter.Cancellable() {
                    @Override
                    public void cancel() throws Exception {
                        textView.removeTextChangedListener(textWatcher);
                    }
                };
                emitter.setCancellation(cancellable);
            }
        }, AsyncEmitter.BackpressureMode.BUFFER); // not quite sure what BackpressureMode would be acceptable
    }
```

Are there potential performance or output differences between the two implementations? `Observable.fromAsnyc()` is still flagged as `Experimental` as well.

(was not sure whether to post this question to RxJava or RxBinding -- will move if this is out of place)

**Comment by JakeWharton** [comment]
> Would implementing `Observable.fromAsync()` with the callback-based view listeners in Android be functionally the same as the `Observable.create()` with `Observable.OnSubscribe<T>` method that RxBinding uses?

Yes. As a library we cannot use it because it's not a stable API though. It's great for use in applications though.

> Are there potential performance or output differences between the two implementations?

No, they will be exactly the same in performance and function.

**Comment by PaulWoitaschek** [comment]
If this gets promoted to the regulären api: which backpressure Mode would be suitable for this library?

**Comment by JakeWharton** [comment]
I would use `NONE` in the library. It's the user's choice (via applying `onBackpressureXxx`) if they want to add backpressure. By default, though, I wouldn't include any (which is what we do now with `create()`).
