### ISSUE TITLE
RxView.clicks(view)

### ISSUE THREAD

**Issue by DomiR** [JakeWharton/RxBinding#275]
Is there a specific reason, why the view is not emitted?

https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding/view/ViewClickOnSubscribe.java#L23

**Comment by gabrielittner** [comment]
There used to be a `RxView.clickEvents(View)` which emitted the view, but it was removed in 0.3.0:

* Fix: Remove binding overloads which provided event objects that included no additional
   information (aside from the source view). To include the source view for an event, add it with
   the `map` operator (e.g., `RxFoo.bar(sourceView).map(data -> new Pair<>(sourceView, data))`).
    * `RxCompoundButton.checkedChangeEvents`
    * `RxRadioGroup.checkedChangeEvents`
    * `RxRecyclerView.scrollStateChangeEvents`
    * `RxView.clickEvents`
    * `RxView.dragEvents`
    * `RxView.focusChangeEvents`
    * `RxView.hoverEvents`
    * `RxView.longClickEvents`
    * `RxView.touchEvents`

**Comment by DomiR** [comment]
I have so much to learn 🙈 

Thanks a lot!
