### ISSUE TITLE
How to implement removeTextChangeListener in RxTextView?

### ISSUE THREAD

**Issue by krupalagile** [JakeWharton/RxBinding#276]
There is nothing I found in the documentation for RxTextView. Should I use ConnectableObserver?

**Comment by JakeWharton** [comment]
Text change listeners are automatically removed when you unsubscribe from the observable.

**Comment by JakeWharton** [comment]
When you call subscribe on the returned observable from a method like `RxTextView.textChanges()` we add the text watcher to the TextView. When you call unsubscribe it is automatically removed. You don't have to do anything beyond use the Observable like any other.

**Comment by krupalagile** [comment]
But how to add then remove and then add TextWatcher again? Do I subscribe then unsubscribe and then subscribe again? Wouldn't it have side effects?

**Comment by JakeWharton** [comment]
Re-subscribing re-adds the text watcher, yes. The act of subscribing and
unsubscribing has the side-effect of adding and removing the watcher.

**Comment by smedic** [comment]
Hi. What I need is to use RxTextView.textChanges and monitor for EditText changes in adapter.
Problem with this is that in onBindViewHolder I must remove text change listener and after setting all views, attach it again. It's simple with TextWatcher, but how to do that with Rx binding?

There is not Subscription anymore, and trying to use disposable.clear() on start and attach RxTextView.textChanges is not functional. It does not emit anything.
