### ISSUE TITLE
RxJava 2.x variant

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#281]
Just a placeholder issue for now.

**Comment by vanniktech** [comment]
Happy to help here

**Comment by chowaikong** [comment]
Support 2.x.x soon? Or wait for the release?

**Comment by anonymouce** [comment]
Getting Ready to Jump into RxJava , Stopped by RxBinding as the first thing I wanted to do . Any way I can use to make a form validation ?

**Comment by JakeWharton** [comment]
This is not a forum for such discussion.

**Comment by gengjiawen** [comment]
@vanniktech Do you have any plan working on this, sir?

**Comment by vanniktech** [comment]
I have time for this however I'll leave it up to Jake. Maybe he planned something already or gave the Rx2 variant any thoughts.

**Comment by marksutt** [comment]
Are there already any plans/road maps?

**Comment by gengjiawen** [comment]
Any update on this ?

**Comment by JakeWharton** [comment]
Updates happen as comments on issues. If there's no new comments, there's
no new updates.

**Comment by kuwork** [comment]
Any update on this?  RxPermissions for Rxjava2 is a good way to deal with rxjava2.

**Comment by JakeWharton** [comment]
Updates happen as comments on issues. If there's no new comments, there's
no new updates.

On Tue, Nov 22, 2016 at 1:14 AM kuwork <notifications@github.com> wrote:

Any update on this? RxPermissions for Rxjava2 is a good way to deal with
rxjava2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/JakeWharton/RxBinding/issues/281#issuecomment-262156881>,
or mute the thread

**Comment by dalewking** [comment]
How about creating a 2.x branch so others can submit PRs against it to assist in the work?

**Comment by erickok** [comment]
Don't forget it's really not hard to create your own bindings, especially with the new style emitters. I started a project, originally for myself, with bindings using RxJava 2, which you may be interested in: https://github.com/erickok/NotRxBinding

I tried to mimic the RxBinding style. Here is the iconic [TextView changes](https://github.com/erickok/NotRxBinding/blob/master/notrxbinding/src/main/java/nl/nl2312/notrxbinding/widget/RxTextView.java) as example (and [its test](https://github.com/erickok/NotRxBinding/blob/master/notrxbinding/src/androidTest/java/nl/nl2312/notrxbinding/widget/RxTextViewTest.java)).

I plan to add many more bindings this week. Feel free to contribute.

**Comment by JakeWharton** [comment]
I'm working on finishing 1.0 in the next week or so. Then `master` will switch to work on 2.x.

**Comment by JakeWharton** [comment]
Started in #316. Feel free to make PRs against that branch. Don't worry about Kotlin or the tests for now.
