### ISSUE TITLE
Usage of RxView.clicks()

### ISSUE THREAD

**Issue by athornz** [JakeWharton/RxBinding#282]
Hi,

I wanted to get some clarity on the usage of RxView.clicks(), and whether it's necessary to unsubscribe.

I've seen multiple usages of RxView.clicks():

**plain:**
```
 RxView.clicks(view)
                    .subscribe(click -> {});
```

**takeUntil:**
```
 RxView.clicks(view)
                    .takeUntil(RxView.detaches(view))
                    .subscribe(click -> {});
```

**subscription:**

```
Subscription subscription = RxView.clicks(view)
                    .subscribe(click -> {});
//unsubscribe somewhere
subscription.unsubscribe();
```

Do we need to unsubscribe?

My particular use case is for a child view in a RecyclerView viewholder. Using RxView.detaches() doesn't fit well, because I don't have a clean way to re bind when the view is attached again.

What are your thoughts?

**Comment by JakeWharton** [comment]
Treat a subscribed `RxView.clicks()` (or any `Observable` from this library for that matter) like you would the `View` reference itself. If you pass it (or subscribe to it) somewhere outside the lifetime of the `View`, you've just leaked your entire activity.

So if you're just subscribing inside your ViewHolder there's no need to unsubscribe just like there'd be no need to unregister a click listener were you doing it manually.

**Comment by athornz** [comment]
Thanks Jake!

**Comment by lewisevans** [comment]
It's just a warning and `@SuppressLint("CheckResult")` will stop these showing
