### ISSUE TITLE
RxBinding need a new action for every click

### ISSUE THREAD

**Issue by zouzhenglu** [JakeWharton/RxBinding#296]
I found I cannot use it to manager all my click code together. I alway setOnClickListenr for the same one ,and than I can create less OnClickListener object.

**Comment by JakeWharton** [comment]
This is not a problem since these objects are so small. You would need to be allocating thousands of click listeners per second before it started to matter. No plans to change this.

**Comment by zouzhenglu** [comment]
thx. #close

**Comment by zouzhenglu** [comment]
thx.
