### ISSUE TITLE
BottomNavigationView binding

### ISSUE THREAD

**Issue by GSala** [JakeWharton/RxBinding#298]
New in the Design Library in the Support Library revision 25.0.0. Should be fairly similar to the NavigationView already available.

https://developer.android.com/reference/android/support/design/widget/BottomNavigationView.html
https://developer.android.com/reference/android/support/design/widget/NavigationView.html

**Comment by JakeWharton** [comment]
PR welcome. Busy for two weeks.

**Comment by alex-townsend** [comment]
I was already working on this -- can have the PR up later today most likely.

**Comment by alex-townsend** [comment]
Looks like there's a bug in the BottomNavigationView that crashes when adding a menu item programmatically (similarly to how it is done in RxNavigationViewTest). Filed a bug report (https://code.google.com/p/android/issues/detail?id=225731).

It works if I actually inflate the menu from XML, so I could do that for the test for now. Or wait to see what the comments are on the bug report. @JakeWharton thoughts? I was trying to keep it as close to what is there for NavigationView already.

**Comment by JakeWharton** [comment]
I assume you're referring to the test? I don't care if it's from XML or
programmatically, so I would opt for whatever works for now. You can leave
a TODO comment with a link to the bug to switch it back if you'd like.

**Comment by JakeWharton** [comment]
Merged.
