### ISSUE TITLE
apply plugin: 'rxbinding-module' 

### ISSUE THREAD

**Issue by ab503044120** [JakeWharton/RxBinding#343]
where is (plugin: 'rxbinding-module') 's source ?  what is the function of it?
 I couldn't find where you use it 
I want to learn about that ,thanks very much

**Comment by JakeWharton** [comment]
It's inside the `buildSrc/` directory. It does automatic generation of the Kotlin sources from the Java sources.

**Comment by ab503044120** [comment]
@JakeWharton thanks for your anwser
