### ISSUE TITLE
Release RxJava2 support

### ISSUE THREAD

**Issue by OrdonTeam** [JakeWharton/RxBinding#350]
Hi,
We would like to ask you to release RxJava2 support. It definitely stopping us in using rx java 2 in our projects.
Is current version releasable in your opinion? If not who can I help you?
How about releasing current version as release candidate?
Karol

**Comment by agramian** [comment]
You can use jitpack to use a specific commit like this 'compile `com.github.JakeWharton.RxBinding:rxbinding:31e02dcaca'`

**Comment by JakeWharton** [comment]
It's not quite ready and I haven't had time to push it across the finish line. Using the SNAPSHOT from master or JitPack is the best option for now.

**Comment by agustinsivoplas** [comment]
Hi @JakeWharton , Do you have an ETA for this? 

Many thanks! 
All the best

**Comment by JakeWharton** [comment]
No
