### ISSUE TITLE
Examples or samples on how to use RxProgressBar

### ISSUE THREAD

**Issue by andre-artus** [JakeWharton/RxBinding#351]
Are there any examples or samples for how to use RxProgressBar? An example in Kotlin would be first prize, but Java would be helpful too. I cannot find anything using Google that's not just the tests in this repo.

**Comment by OrdonTeam** [comment]
Do you mean something like that?
`downloadBytesProgerssObservable`
`    .map{ it * 100 / fileSizeInBytes }`
`    .subscribe(RxProgressBar.progress(progressBarView))`

**Comment by JakeWharton** [comment]
All of the methods returning Observables correspond to listeners and all of the methods returning Actions correspond to the setters on the target type. You should use them the same way you would use those listeners and setters.

**Comment by andre-artus** [comment]
Thanks guys, this helps.
