### ISSUE TITLE
Proposal: Rename Notification to RxBindingNotification or something more distinct

### ISSUE THREAD

**Issue by hzsweers** [JakeWharton/RxBinding#358]
We and others use the same `Notification` enum pattern with the same name, would be nice to make this more distinct.

This is also why I was advocating for [this](https://github.com/ReactiveX/RxJava/issues/4652#issuecomment-254281935) ☹️

**Comment by hzsweers** [comment]
It has the same name and looks inviting on autocomplete. Same way I'd advocate for libraries to prefix their Preconditions or Util classes, generic name that's likely to match others invites misuse I think. Not that big of a deal since it happens a lot anyway, but in this case I worry they could end up referenced in the same file a lot and force one to be fully qualified. Just potentially messy/confusing since it's public and part of the API.

**Comment by JakeWharton** [comment]
So are you also proposing we prefix the Preconditions class because we have
one of those too?

**Comment by hzsweers** [comment]
I would if it were part of the public API yeah. They're unlikely to be used/imported outside of rxbinding in this case though.

**Comment by JakeWharton** [comment]
Well both are `public` but neither are part of the public API.

Also I just [restricted their use][1] to the library. Is that enough?

 [1]: https://github.com/JakeWharton/RxBinding/pull/360

**Comment by artem-zinnatullin** [comment]
Where I can find your proposal on renaming java.util.Observable?

Just kidding, sorry. Btw, you can exclude things from auto-complete
suggestions in IntelliJ, and probably even share exclude-list with the team
through version control.

**Comment by hzsweers** [comment]
Actually I completely missed that this was only internal, I thought the public factories returned Observable<Notification> as well. In that case, not a problem at all and the restrictto annotations help as well :+1:
