### ISSUE TITLE
Cannot access class 'com.jakewharton.rxbinding2.InitialValueObservable'

### ISSUE THREAD

**Issue by bmoliveira** [JakeWharton/RxBinding#359]
I'm using the RxBinding-Snapshot version and after the latest snapshot build, this started to happening any ideas why this started to happen?

Complete error:
Error:(126, 25) Cannot access class 'com.jakewharton.rxbinding2.InitialValueObservable'. Check your module classpath for missing or conflicting dependencies

**Comment by JakeWharton** [comment]
The [CI build that uploads snapshots succeeded][1] so it should be present in the core 'rxbinding' module. Perhaps you caught it in the middle of uploading. Can you try again with `--refresh-dependencies`?

 [1]: https://travis-ci.org/JakeWharton/RxBinding/jobs/199868799
