### ISSUE TITLE
New RxView.post method

### ISSUE THREAD

**Issue by bryant1410** [JakeWharton/RxBinding#371]
It'd be cool if there is a `RxView.post(view)` method available, which internally calls `view.post`. It could be chained with view state checks and with other operators.

**Comment by JakeWharton** [comment]
This doesn't fit with the theme of the library which is binding view properties. `View.post()` is a shorthand for `new Handler(Looper.getMainLooper()).post()` which is what RxAndroid's `AndroidSchedulers.mainThread()` wraps and so using `subscribeOn` and/or `observeOn` with `mainThread()` will have the same effect as `View.post()`.

**Comment by artem-zinnatullin** [comment]
According to source code of `android.view.View`, `View.post()` actually behaves slightly different from `new Handler(Looper.getMainLooper()).post()`:

* If `View` is not attached to a `Window`  it'll put `Runnable` into a queue and will process this queue once `View` will be attached.
* if `View` is attached to a `Window` already, then yes — `View.post()` will behave as `new Handler(Looper.getMainLooper()).post()`.
