### ISSUE TITLE
RxView.clicks  and RxView.touches  used at the same time, only RxView.touches is useful

### ISSUE THREAD

**Issue by fengdesola** [JakeWharton/RxBinding#373]
Hi Jake and everyone! Thanks for excellent job!

I think RxView.touches intercepted android event.How to change?

Here is the my code:
`RxView.clicks(tvEffect).subscribe(o-> {showToast("click effect");});`

`
ConnectableObservable<MotionEvent> motionEventObservable = RxView.touches(v).publish();

        // Capture down events
        motionEventObservable
                .filter(new Predicate<MotionEvent>() {
                    @Override
                    public boolean test(@NonNull MotionEvent motionEvent) throws Exception {
                        return motionEvent.getAction() == MotionEvent.ACTION_DOWN;
                    }
                }).subscribe(new Consumer<MotionEvent>() {
                    @Override
                    public void accept(@NonNull MotionEvent motionEvent) throws Exception {
                        ObjectAnimator.ofFloat(v, "alpha",1.0f,0.3f).start();
                    }
                });
        // Capture up/cancel events
        motionEventObservable
                .filter(new Predicate<MotionEvent>() {
                    @Override
                    public boolean test(@NonNull MotionEvent motionEvent) throws Exception {
                        return motionEvent.getAction() == MotionEvent.ACTION_UP
                                || motionEvent.getAction() == MotionEvent.ACTION_CANCEL;
                    }
                }).subscribe(new Consumer<MotionEvent>() {
            @Override
            public void accept(@NonNull MotionEvent motionEvent) throws Exception {
                ObjectAnimator.ofFloat(v, "alpha",0.3f,1.0f).start();
            }
        });
        motionEventObservable.connect();`

**Comment by Joseph82** [comment]
Yes, the implementation of the `onTouch()` for the listener inside `ViewTouchObservable` will always consume all the emitted events, returning `true`, and this will prevent click events to be fired.

I think the only thing that you can do is to remove the click listener and recognize the click event using the motion events emitted from the Observable.

**Comment by JakeWharton** [comment]
There's an overload for `RxView.touches` which takes two parameters: the source view and also a function which specifies the value to return. When you use the single-parameter version it always returns `true`, like @Joseph82 said. If you want the touch even to otherwise be propagated then you need to implement the two parameter version and return `false` for some or all events.

**Comment by fengdesola** [comment]
@Joseph82 @JakeWharton  thanks!
After reading ViewTouchObservable, I know why.
