### ISSUE TITLE
RxView.clicks doOnSubscribe run when Activity onCreate

### ISSUE THREAD

**Issue by wjkjinke00** [JakeWharton/RxBinding#374]
`RxView.clicks(mButton)
                .flatMap(new Function<Object, ObservableSource<Long>>() {
                    @Override
                    public ObservableSource<Long> apply(Object o) throws Exception {
                        return Observable.interval(0, 1, TimeUnit.SECONDS, AndroidSchedulers.mainThread()).take(timeL);
                    }
                })
                .map(new Function<Long, Long>() {
                    @Override
                    public Long apply(Long aLong) throws Exception {
                        return timeL - aLong - 1;
                    }
                })
                .doOnSubscribe(new Consumer<Disposable>() {
                    @Override
                    public void accept(Disposable disposable) throws Exception {
                        Observable.just("a").delay(5, TimeUnit.SECONDS)
                                .subscribe(new Consumer<String>() {
                                    @Override
                                    public void accept(String s) throws Exception {
                                        Log.d("MainActivity", s + "-SECONDS");
                                    }
                                });
                    }
                })
                .subscribe(new Observer<Long>() {
                    @Override
                    public void onSubscribe(Disposable disposable) {
                        Log.d("MainActivity", "onSubscribe");
                        mSendCodeDisposable = disposable;
                    }

                    @Override
                    public void onNext(Long aLong) {
                        Log.d("MainActivity", "aLong:" + aLong);
                        if (aLong > 0l) {
                            mButton.setEnabled(false);
                            mButton.setText(aLong + "");
                        } else {
                            mButton.setEnabled(true);
                            mButton.setText("button");
                            onComplete();
                        }
                    }

                    @Override
                    public void onError(Throwable throwable) {
                        throwable.printStackTrace();
                    }

                    @Override
                    public void onComplete() {
                        Log.d("MainActivity", "onComplete");
                    }
                });`

the method doOnSubscribe  run  when activity onCreate
I want to click on the button when the network request, and display countdown on the button

**Comment by JakeWharton** [comment]
This is a general RxJava usage question and not anything specific to RxBinding. Please use the normal places for seeking general help with RxJava: its mailing list or on StackOverflow with the 'rxjava' tag.

**Comment by wjkjinke00** [comment]
Thanks
