### ISSUE TITLE
Why do the Observables "extend Observable" instead of using Observable.create()?

### ISSUE THREAD

**Issue by Zhuinden** [JakeWharton/RxBinding#375]
In RxBinding1, the observables were created using `Observable.create()` (now called `Observable.unsafeCreate()`).

While it made sense that they were never changed to `Observable.fromEmitter()` for compatibility reasons; I'm wondering: why use `extends Observable` (and `extends MainThreadDisposable` on listener) instead of `Observable.create(ObservableEmitter)` and creating a `MainThreadDisposable` that wraps it?

I check the source code of RxBinding for Rx-best-practices and I was somewhat surprised that it works so _differently_ compared to Rx1 implementation.

**Comment by vanniktech** [comment]
https://github.com/JakeWharton/RxBinding/pull/316#issuecomment-265414491

**Comment by Zhuinden** [comment]
Understood.
