### ISSUE TITLE
Is it possible to throttle a collection of RxViews?

### ISSUE THREAD

**Issue by geft** [JakeWharton/RxBinding#376]
I have multiple throttled buttons. Is there a fast way to throttle them all so pressing the first button prevents button clicks on all other buttons for a duration of time?

**Comment by Thomvis** [comment]
No, unless you map each of them individually to a unique value (int, enum, or something else), merge those together and throttle on the result.

**Comment by JakeWharton** [comment]
This is a general RxJava question and not specific to RxBinding. If you need further help please use StackOverflow or the RxJava mailing list.
