### ISSUE TITLE
cannt use rxtextview with edittext

### ISSUE THREAD

**Issue by elirangoshen** [JakeWharton/RxBinding#377]
How i can use RxTextView.textchangevents with EditText ? that only gets textview.

i'm using it for login form and it actually TextInputEditText.

**Comment by liminal** [comment]
TextInputEditText extends AppCompatEditText which extends EditText which extends TextView 

So RxTextView.textChangeEvents should work. Have you tried it?

**Comment by JakeWharton** [comment]
Please provide a sample that demonstrates the problem. Otherwise what @liminal said it correct.
