### ISSUE TITLE
Private member access between outer and inner classes

### ISSUE THREAD

**Issue by oldergod** [JakeWharton/RxBinding#379]
I noticed some inner classes' private members were access from the outer class. e.g. in [RecyclerViewScrollEventObservable.java](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding-recyclerview-v7/src/main/java/com/jakewharton/rxbinding2/support/v7/widget/RecyclerViewScrollEventObservable.java#L23)

If you would welcome a fix, I could send a PR as I am reading a lot of the code these days anyway.

**Comment by JakeWharton** [comment]
Sure
