### ISSUE TITLE
RxBinding2 how to use

### ISSUE THREAD

**Issue by Flywhiter** [JakeWharton/RxBinding#387]
only import rxbinding2 couldnt find Action1
import rxjava2 Compile error
could give some example

**Comment by Edward608** [comment]
RxBinding 2 uses RxJava2, in which Action1 is renamed to Consumer.

**Comment by JakeWharton** [comment]
Yep see https://github.com/ReactiveX/RxJava/wiki/What%27s-different-in-2.0#actions for more info.
