### ISSUE TITLE
Cognitive Load

### ISSUE THREAD

**Issue by santwanaverma15** [JakeWharton/RxBinding#388]
I m new to programming and have started using RxBinding about two weeks ago. According to me RxBinding somewhere increases the cognitive load of the code by actually increasing the number of lines for the same thing which can be done in one line previously.
ex. toolbar.setTitle("some string");
same with RxBinding
RxToolbar.title
              .accept("some string");

I sthere a way to use RxBinding wihtout increasing the cognitive load ?

**Comment by JakeWharton** [comment]
You should not be using it for that. The Consumers are exposed such that you can subscribe them to an RxJava stream.

e.g.,
```java
someStream.subscribe(RxToolbar.title(toolbar));
```
which otherwise would be
```java
someStream.subscribe(new Consumer<String>() {
  @Override public void accept(String s) {
    toolbar.setTitle(s);
  }
});
```
If you have lambdas and method references just do
```java
someStream.subscribe(toolbar::setTitle)
```
and don't use RxBinding at all.

**Comment by santwanaverma15** [comment]
Thanks for the suggestions ! Is there a way I can decide when to use RxBinding and when not while at this stage. I feel RxBinding but I need to understand it fully to actually make a difference with it.
