### ISSUE TITLE
Preconditions.checkMainThread doesn't call onSubscribe

### ISSUE THREAD

**Issue by akarnokd** [JakeWharton/RxBinding#391]
The [method](https://github.com/JakeWharton/RxBinding/blob/master/rxbinding/src/main/java/com/jakewharton/rxbinding2/internal/Preconditions.java#L32) doesn't call `onSubscribe` before it signals the error about being on the wrong thread which can cause `NullPointerException` elsewhere in the chain (hiding the original error). I haven't checked all invocation places but it seems the method is always called before otherwise interacting with the downstream observer thus calling `onSubscribe` with some no-op `Disposable` should be safe.

Related: https://github.com/ReactiveX/RxJava/issues/5435

**Comment by JakeWharton** [comment]
Thanks! Can fix.
