### ISSUE TITLE
Kotlin view extension functions get WrongViewCast lint error

### ISSUE THREAD

**Issue by ferhatparmak** [JakeWharton/RxBinding#399]
When I compile my app against api 26, i can use generics for findViewById method but when I write this code:

`findViewById<Button>(R.id.button_run).clicks()`

I get "Unexpected implicit cast to Unit" lint error message.

Is this a lint bug or am I missing something?

**Comment by JakeWharton** [comment]
Seems like a lint bug. Does it work at runtime?

**Comment by ferhatparmak** [comment]
Yes, its is working.

**Comment by JakeWharton** [comment]
I would file a bug on b.android.com/new then.

**Comment by JakeWharton** [comment]
Can you link the bug so I can star it?

**Comment by ferhatparmak** [comment]
Issue link,
https://issuetracker.google.com/issues/63968954

**Comment by JakeWharton** [comment]
Thanks!
