### ISSUE TITLE
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

### ISSUE THREAD

**Issue by mateusgrb** [JakeWharton/RxBinding#402]
The project I'm working on is stuck on `compileSdkVersion 23` for dependency reasons. My `buildToolsVersion`is set to `25.0.2`. Under my dependencies I have `compile 'com.android.support:support-v4:23.4.0'`.

With only `compile 'com.jakewharton.rxbinding2:rxbinding-support-v4:2.0.0'`, everything works good.

Now I want to use `RxSearchView`from appcompat-v7. When I add `compile 'com.jakewharton.rxbinding2:rxbinding-appcompat-v7:2.0.0'`, I get these errors:

> /Users/a/Documents/project/build/intermediates/res/merged/armv7/debug/values-v24/values-v24.xml
> Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
> Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
> Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
> Error:(4) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

It seems like the latest version requires compileSdkVersion higher than 23. Is there anyway to workaround that?

**Comment by JakeWharton** [comment]
rxbinding-appcompat-v7 is pulling in a newer version of AppCompat which is what is causing this problem. You can use a [Gradle `ResolutionStrategy`][1] to force the support library versions you are pulling in to an older version (like [this][2]).

 [1]: https://docs.gradle.org/4.1/dsl/org.gradle.api.artifacts.ResolutionStrategy.html
 [2]: https://github.com/JakeWharton/u2020/blob/e43f8b896c66e6364c82295eebca54742cfb3958/build.gradle#L105-L113
