### ISSUE TITLE
Listen to checkChanges() on CheckedTextView

### ISSUE THREAD

**Issue by jemaystermind** [JakeWharton/RxBinding#403]
I can't seem to find how to listen for a check changes on a CheckedTextView. I've seen `RxCheckedTextView` but it doesn't provide a method for a check changes.

I tried something like `RxView.clicks(checkedtextview).flatMap<Boolean> { Observable.just(checkedtextview.isChecked)}` but it can't register a click on a `CheckedTextView` even though `android:clickable` is set to `true`.

**Comment by JakeWharton** [comment]
How would you do it normally? I don't see an associated callback for being notified of the change.

**Comment by artem-zinnatullin** [comment]
>I don't see an associated callback for being notified of the change.

Doesn't look like a valid excuse for a Framework Engineer :trollface:

**Comment by oldergod** [comment]
You should be able to use `RxView.clicks`. The problem is the resulted observable does not emit the view so you would need to check its state via side effect. _I don't know why it's been decided a void value, instead of the view itself, would get emitted back to the stream though_

This should do it: `RxView.clicks(checkedtextview).map { checkedtextview.isChecked }`

**Comment by JakeWharton** [comment]
Views in streams is a really bad default! You're begging for unintentional leaks to optimize for the rare case where you actually care about the view instance.

**Comment by jemaystermind** [comment]
I should've added more details. I have this registration form that needs validation before enabling the "Confirm" button to process the registration. This form contains `EditText`s and "Accept license agreement" `CheckedTextView`. 

What I want is add the agreement as part of the validation together with the `EditText`s where if it's unchecked, the "Confirm" button will be disabled. 

I tried what @oldergod suggested and modified it a bit since it doesn't update the check mark on the actual UI but I can receive updates if the view is being clicked. Don't know why. It looked something like this `RxView.clicks(checkedtextview).map{ checkedtextview.isChecked = !checkedtextview.isChecked }.map { checkedtextview.isChecked }`. It looks ugly to me but it works!
