### ISSUE TITLE
What are the various kinds of bindings?

### ISSUE THREAD

**Issue by RobLewis** [JakeWharton/RxBinding#408]
Can you describe the difference between "platform bindings", "'support-v4' library bindings", "'appcompat-v7' library bindings" and so on? As a practical matter for someone wanting to build an Android app with RxJava, what does it all mean? 

Naive question: for basic applications, might it be simpler to replace typical Android event listeners with calls to a PublishSubject, allowing any interested parties to subscribe to notifications?

**Comment by liminal** [comment]
platform-bindings = bindings for views and widgets that are part of the android platform
support-v4 library bindings = bindings for views and widgets that are part of the support-v4 library. etc
(see https://developer.android.com/topic/libraries/support-library/packages.html for what the support libraries do)

RxBindings is split up into separate packages per support library so you can include just the bindings for the set of support libraries you are using.

**Comment by RobLewis** [comment]
Thanks for the tips! Any comment on my other question?

**Comment by JakeWharton** [comment]
I don't think using a subject is any simpler since you now have to manage both the listener and subject instances instead of a single observable. You can certainly do that if you don't have access to this library for whatever reason but given both I wouldn't prefer it.
