### ISSUE TITLE
Kotlin bindings lack @TargetApi/@RequiresApi annotations

### ISSUE THREAD

**Issue by joshfriend** [JakeWharton/RxBinding#410]
Just had an issue with the lack of `View.OnScrollChangeListener` causing crashes on pre-M devices when calling `view.scrollChangeEvents()`. The [java bindings](https://github.com/JakeWharton/RxBinding/blob/b0c8a66128e17be9924c2443345ae41d54729386/rxbinding/src/main/java/com/jakewharton/rxbinding2/view/RxView.java#L300) correctly specify `@RequiresApi(M)`, but the [kotlin bindings](https://github.com/JakeWharton/RxBinding/blob/b0c8a66128e17be9924c2443345ae41d54729386/rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/view/RxView.kt#L219) do not retain these annotations so the android linter doesn't warn you about the potential crash.

**Comment by JakeWharton** [comment]
Related to #393.

**Comment by JakeWharton** [comment]
Fixed on master
