### ISSUE TITLE
DebouncingClickListener

### ISSUE THREAD

**Issue by ZakTaccardi** [JakeWharton/RxBinding#411]
ButterKnife uses [DebouncingClickListener](https://github.com/JakeWharton/butterknife/blob/master/butterknife/src/main/java/butterknife/internal/DebouncingOnClickListener.java) by default. Is there a good reason this lib doesn't?

One solution:
* `.clicks()` (behavior change) - replace current implementation with the debouncing solution
* `.asyncClicks()` (new api) - replicates current implementation of `.clicks()`

Another:
* `.debouncedClicks()` (new api) - uses `DebouncingClickListener` instead

If you're interested in a PR for this, I'd be happy to do it

**Comment by JakeWharton** [comment]
See #401
