### ISSUE TITLE
RxtextView textChangeEvents calls onNext twice for every change

### ISSUE THREAD

**Issue by topeomot2** [JakeWharton/RxBinding#415]
Hello, below is the code I am testing
`RxTextView.textChangeEvents(searchEditText)
                .subscribe({t: TextViewTextChangeEvent? ->  Logger.i("onNext")},
                        {t: Throwable? ->  Logger.i("onError")},{Logger.i("onComplete")})`

In logcat  I get "onNext" printed in the logs for every change in the editView. Is this how it is suppose to work?

**Comment by JakeWharton** [comment]
Does it happen when not using RxBinding?

**Comment by topeomot2** [comment]
Yes, it happened when I used a normal textwatcher with the addTextChangedListener. I am using Anko DSL for my layouts, I will go through my code and see where the issue is.
Thanks

**Comment by topeomot2** [comment]
I am using orhanobut/logger for logging. When I changed it to the normal Java Logger the issue stopped. Thanks for your help.
