### ISSUE TITLE
RxView.clicks(textview)  how to get the textview instance?

### ISSUE THREAD

**Issue by parcool** [JakeWharton/RxBinding#418]
as the title,i have the codes:
```java
//not findViewById but new TextView
TextView textView = new TextView(Context);
//...
RxView.clicks(textView)
            .subscribe(object -> {
//there,how can i get the textview itself?because i want to get it's text?
});
```

**Comment by Joseph82** [comment]
`RxView.clicks` Observable emits events which meaning is "hey, a click happened", there is no payload in the event. 

If you want to get the text when the click event is triggered, just use your: `TextView`

`textView.getText()`

**Comment by parcool** [comment]
@Joseph82 it's a for-loop and the textview is not a single.so textView.getText() is.....?

**Comment by Joseph82** [comment]
@parcool If so can `map` your event into the String that you need:

```
RxView.clicks(view).map(o -> view.getText().toString())
        .subscribe(s -> printString(s));
```

**Comment by parcool** [comment]
@Joseph82  thanks anyway, i will try.

**Comment by parcool** [comment]
@Joseph82   thank you so so much!it's work!forgive me what a novice i am.
