### ISSUE TITLE
Dispose of SeekBarChangeObservable

### ISSUE THREAD

**Issue by RicardoBelchior** [JakeWharton/RxBinding#419]
https://github.com/JakeWharton/RxBinding/blob/24b73f4d2f929cc732d1e7b64e6b900241fb2205/rxbinding/src/main/java/com/jakewharton/rxbinding2/widget/SeekBarChangeObservable.java#L58

I'm just curious, why is SeekBarChangeObservable.Listener#onDispose setting the listener once again? 

Instead of: `view.setOnSeekBarChangeListener(this); `
Shouldn't it be `view.setOnSeekBarChangeListener(null); ` ?

**Comment by JakeWharton** [comment]
Yep! Send a PR?

**Comment by RicardoBelchior** [comment]
ok
