### ISSUE TITLE
How to use FAB extension function

### ISSUE THREAD

**Issue by benwicks** [JakeWharton/RxBinding#435]
https://github.com/JakeWharton/RxBinding/blob/41fa0a79827fa4b93a0daf9a3406f524b34c1052/rxbinding-design-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/support/design/widget/RxFloatingActionButton.kt#L17

I'm trying to use this `visibility` extension function but it looks like it conflicts with `View#getVisibility`.

Here's my usage:
```
viewModel.loading()
    .map { loading -> !loading }
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe(actionButton.visibility())
```

**Comment by JakeWharton** [comment]
Otherwise you can use RxFloatingActionButton.visibility(actionButton) as a
workaround.

**Comment by benwicks** [comment]
Ok I found out how to import it correctly now. Thanks!
```
import com.jakewharton.rxbinding2.support.design.widget.visibility
```
