### ISSUE TITLE
Could not find com.android.support:support-annotations:27.0.2.

### ISSUE THREAD

**Issue by turing-king** [JakeWharton/RxBinding#436]
`Error:Could not find com.android.support:support-annotations:27.0.2.
Required by:
    project :app

Please install the Android Support Repository from the Android SDK Manager.
<a href="openAndroidSdkManager">Open Android SDK Manager</a>`

My adk tools are up to date

**Comment by JakeWharton** [comment]
Add `google()` to your repositories in your `build.gradle`.
