### ISSUE TITLE
Unable to subscribe an Observable declared as lazy (Kotlin).

### ISSUE THREAD

**Issue by uburoiubu** [JakeWharton/RxBinding#443]
Have this as a class field: 

`private val logOutObservable by lazy {  RxView.clicks(root.logOutButton).throttleFirst(500, TimeUnit.MILLISECONDS) }`

Trying to `subscribe()` then in `OnCreateView()`. Subscription does not work.

**Comment by JakeWharton** [comment]
Can you provide a failing test case or executable sample? I can't reproduce.
