### ISSUE TITLE
Textwatcher for AutoCompleteTextView

### ISSUE THREAD

**Issue by sagarnayak** [JakeWharton/RxBinding#444]
I want to add a text watcher to the AutoCompleteTextView with a debounce functionality. how can i do that by RxAutoCompleteTextView.  please do help.

**Comment by JakeWharton** [comment]
You can use `RxTextView.textChanges` to get access to input events and then the normal RxJava operators for deboucing however you see fit. For general RxJava help in deboucing please use StackOverflow with the 'rx-java' tag or post to the RxJava mailing list.
