### ISSUE TITLE
Don't emit event from `RxTextView.textChanged()` when the underlying `TextView` is updated programatically

### ISSUE THREAD

**Issue by skykelsey** [JakeWharton/RxBinding#445]
It would be great if there was a way to prevent all bindings from emitting events when they are not updated through actual user interaction.

https://stackoverflow.com/a/33151589/560600

**Comment by JakeWharton** [comment]
This library is just a reactive wrapper around the normal callbacks. Since the normal callbacks are invoked when text is set programmatically, so are events emitted into the reactive stream. Suppressions of said events can't be done as part of the library.
