### ISSUE TITLE
RxView.clicks failed when request occrus to an error.

### ISSUE THREAD

**Issue by showwiki** [JakeWharton/RxBinding#446]
My code is underlying,when the network request checkCustTel throw Error Exception .   RxView.clicks(iv_phones) will never respose to my clicks.  Any solution?

RxView.clicks(iv_phones)
                .subscribeOn(AndroidSchedulers.mainThread())
                .observeOn(Schedulers.io())
                .switchMap(restResult ->   checkCustTel(item.getCustBasicDelId()))
                .compose(new RxHelper<RestResult>(mContext).scheduleAndLifeCircle())
                .subscribe(new BaseDisposableObserver<RestResult>(){
                    @Override
                    public void onNext(RestResult restResult) {
                        super.onNext(restResult);
                        doCallPhone(item, activity, sfm);
                    }
                });

**Comment by JakeWharton** [comment]
An error is a terminal event which will cause the upstream to unsubscribe. You'll need to recover from the error inside the switchMap so that the outer stream never sees a terminal event.
