### ISSUE TITLE
RxView.Clicks does not support DisposableSingleObserver ?? 

### ISSUE THREAD

**Issue by taeyoung4808** [JakeWharton/RxBinding#448]
this is my code: 

![2018-06-21 4 51 59](https://user-images.githubusercontent.com/6241817/41705367-bed6f8ee-7573-11e8-877d-563d04e4433f.png)

rxbinding clicks does not support DisposableSingleObserver ?

**Comment by Joseph82** [comment]
You are actually trying to subscribe to an `Observable`, so you should use `DisposableObserver` and not `DisposableSingleObserver`. Unless you convert your source of data into `Single` before subscribing.

**Comment by taeyoung4808** [comment]
@Joseph82 

1. sorry for my english level..

2. i can't understand.. 
lnbFaceBook.startLogin() method return "Single.create", so loginResult is not it Single type?? 

"Single data" mean is not it  Single.create ? 

if then "Single data" is Single Object?

**Comment by JakeWharton** [comment]
`Observable.switchMapSingle` still returns an `Observable`. If you only want a single click you need to call something like `single()` or `first()` in the stream.
