### ISSUE TITLE
AndroidX Jetpack

### ISSUE THREAD

**Issue by carmas123** [JakeWharton/RxBinding#450]
Any news about AndroidX support?

**Comment by JakeWharton** [comment]
Jetifier should handle it

**Comment by nhaarman** [comment]
I created an issue a while back on the Android tracker addressing some issues with Kotlin extension functions: https://issuetracker.google.com/issues/79443876

> The 'rxbinding-design-kotlin' artifact provides the following two extension functions:
> 
>  - fun android.view.View.dismisses(): Observable<View>
>  - fun android.support.design.widget.Snackbar.dismisses(): Observable<Int>
> 
> Both functions reside in the same package: 'com.jakewharton.rxbinding2.support.design.widget'
> 
> The following code snippet does not compile:
> 
>       import com.google.android.material.snackbar.Snackbar
>       import com.jakewharton.rxbinding2.support.design.widget.dismisses
>       
>       class Foo {
>       
>           fun bar(n: Snackbar) {
>               n.dismisses().subscribe {}
>           }
>       }
> 
> The compiler error:
> 
>     /app/src/main/java/com/example/issuerepro/Foo.kt: (9, 11): Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
>     public inline fun Snackbar.dismisses(): Observable<Int> defined in com.jakewharton.rxbinding2.support.design.widget
>     @CheckResult public inline fun View.dismisses(): Observable<View> defined in com.jakewharton.rxbinding2.support.design.widget

**Comment by carmas123** [comment]
When I try to use a simple RX binding like this:

`RxSearchView.queryTextChangeEvents(searchView)`

I got this error: 

> Type mismatch.
> Required: android.widget.SearchView
> Found: androidx.appcompat.widget.SearchView

**Comment by carmas123** [comment]
Solved...thankyou

**Comment by ko3ak1990** [comment]
@

> Solved...thankyou

@carmas123 How did you solve it?

**Comment by carmas123** [comment]
Try the alpha release

**Comment by adamvietnam** [comment]
> When I try to use a simple RX binding like this:
> 
> `RxSearchView.queryTextChangeEvents(searchView)`
> 
> I got this error:
> 
> > Type mismatch.
> > Required: android.widget.SearchView
> > Found: androidx.appcompat.widget.SearchView

Hi - I'm having the same issue. Do you recall how you resolved this please?
