### ISSUE TITLE
Deprecated consumers can't be replaced by method references

### ISSUE THREAD

**Issue by gabrielhuff** [JakeWharton/RxBinding#455]
On ea3a2fab, some consumers got deprecated so that people use method references instead.

However, this doesn't work for consumers such as [`MenuItem.visible()`](https://github.com/JakeWharton/RxBinding/blob/4e100d443d1eefee75aa32f3c9e85883a038c97e/rxbinding-kotlin/src/main/kotlin/com/jakewharton/rxbinding2/view/RxMenuItem.kt#L139) since the underlying method ([`MenuItem.setVisible(Boolean)`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/MenuItem.java#550)) does not return `void`/`Unit `, which would be the type required by the `subscribe` method:

<img width="615" alt="screen shot 2018-08-03 at 07 45 27" src="https://user-images.githubusercontent.com/19377340/43626245-4b0128aa-96f1-11e8-9064-f59395524836.png">

I haven't checked if `MenuItem.visible()` is the only method affected by this issue, maybe there are more.

**Comment by JakeWharton** [comment]
This is a language deficiency of Kotlin. You can vote for return type coercion to `Unit` here: https://youtrack.jetbrains.com/issue/KT-11723. In these cases you are still able to use a lambda which remains no longer than the convenience functions previously exposed by this library.
