### ISSUE TITLE
Emits once when I `cast` 

### ISSUE THREAD

**Issue by aliaziz** [JakeWharton/RxBinding#456]
Hello Jake and team. Thanks for the great work done.
Noticed something.
Casting with `as` emits only once and stops emitting: For example.
```  
RxTextView.textChanges(phoneNumberEditText)
                .skipInitialValue()
                .subscribe {text ->
                    purchaseButton.isEnabled = purchaseViewModel.isNumberValid(text as String)
                }
```

**But when i do this, it works fine**
```
RxTextView.textChanges(phoneNumberEditText)
                .skipInitialValue()
                .subscribe {text ->
                    purchaseButton.isEnabled = purchaseViewModel.isNumberValid(text.toString())
                }
```

**Comment by nobodysfault** [comment]
Probably it's because your cast throws ClassCastException (cause CharSequence isn't necessarily a String), observable emits error notification and stops emitting items.
