### ISSUE TITLE
Null parameter when disposing a custom View written in Kotlin

### ISSUE THREAD

**Issue by Orbyt** [JakeWharton/RxBinding#457]
Given a simple custom view:
```
class Button @JvmOverloads constructor(
    context: Context, attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : FrameLayout(context, attrs, defStyleAttr) {

    init {
        View.inflate(context, R.layout.button, this)
    }

    override fun setOnClickListener(listener: View.OnClickListener) =
        button.setOnClickListener(listener)
}
```

When this `View` is used in an `Activity` with RxBinding, an eventual call to [View#setOnClickListener](https://github.com/JakeWharton/RxBinding/blob/88092a168a5bb25920418208ea5a29558ae6e286/rxbinding/src/main/java/com/jakewharton/rxbinding2/view/ViewClickObservable.java#L44) passing `null` would result in the `View`'s `setOnClickListener` method to be invoked with a `null` argument, causing the following error:

> Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull

**Comment by JakeWharton** [comment]
Change your override to accept a nullable listener. `null` is a valid value here.
