### ISSUE TITLE
Butterknife or Rxbinding?

### ISSUE THREAD

**Issue by strongmanb** [JakeWharton/RxBinding#459]
My project used rxjava, so butterknife or rxbinding which I choose is better?

**Comment by JakeWharton** [comment]
It's not really an either/or. Butter Knife binds views to field. RxBinding exposes listener events as Rx streams. You can use both. You can use only Butter Knife and callbacks. You can use findViewById and only RxBindings. Or you can use neither. What you choose depends on what you want your code to look like and what libraries you are using and only you can make that decision.
