### ISSUE TITLE
Release Kotlin snapshot

### ISSUE THREAD

**Issue by pardom** [JakeWharton/RxBinding#46]
It appears that only the Java artifacts have been released to the snapshot repo. Do you plan to release the Kotlin version to snapshots as well?

**Comment by JakeWharton** [comment]
Yes

**Comment by pardom** [comment]
Great, thanks!

**Comment by JakeWharton** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/jakewharton/rxbinding/
