### ISSUE TITLE
Upgrade to androidx

### ISSUE THREAD

**Issue by chris-horner** [JakeWharton/RxBinding#460]
The android x libraries are currently at release candidate versions so I figured it'd be a good time to discuss this. Hopefully migrating RxBinding will just involve a whole lot of renaming of imports, but what will this mean for the version number? This is technically a breaking change for some of the modules, so does this mean we change to 3.0?

Happy to some some legwork here, I just want to know how this should be approached. Are there any other considerations when migrating? Or is the plan to just let Jetifier handle things for now?

**Comment by JakeWharton** [comment]
I was planning to update everything once 1.0 hits which should be any day now. We can bump the version to 3.0.0-SNAPSHOT and start the work

**Comment by JakeWharton** [comment]
Who's ready?!?

**Comment by JakeWharton** [comment]
How much would it offend people if this 3.0 was Kotlin-first as well?

**Comment by feinstein** [comment]
I am avoiding Kotlin, since I belive its going to be a waste of time converting all my code base to Kotlin and then converting it all over again to Flutter, a short while afterwards.

I don't get offended if you go Kotlin first, I just don't get why to go to all the trouble if in a year or less people will be switching platforms anyways. Better focus the energy on making a Dart version and accelerate the future?

**Comment by feinstein** [comment]
Why not?

I would love to hear your point of view about this, since you are so much more involved into Android than anyone I know.

**Comment by JakeWharton** [comment]
I don't want to have the discussion here. The easiest justification is that
it's a random third-party framework and not a first-party Android one.

**Comment by PaulWoitaschek** [comment]
AndroiX is stable :)

**Comment by dadino** [comment]
Is there a workaround for the androidx Toolbar while we wait for the new version of RxBinding?

**Comment by offbow** [comment]
Any updates on a 3.0 snapshot?

**Comment by wingu-wiktor** [comment]
Is "android.enableJetifier=true" in gradle.properties sufficient for now to use with RxBinding? 
I mean before releasing 3.0

**Comment by JakeWharton** [comment]
This is done on `master` as 3.0.0-SNAPSHOT
