### ISSUE TITLE
API 14

### ISSUE THREAD

**Issue by hzsweers** [JakeWharton/RxBinding#48]
Back with this again, sorry again :/

All the current tests pass whenever I try with API 14, and I [can't find](http://developer.android.com/about/versions/android-4.0.3.html) any significant UI changes between 14 and 15 that would impose a limitation on this library in the future. 

Totally understand if you'd rather not though, just putting it up for consideration!

**Comment by JakeWharton** [comment]
I choose 15 by default for everything. There's no reason to support anything less in 99.99% of reasonable cases. That said, send a PR for this and I'll merge it.

**Comment by hzsweers** [comment]
Totally agree, it's just inertia for us since we have a ton of users ([1 million...](https://github.com/JakeWharton/ProcessPhoenix/issues/2)) still on API 14 devices for some reason.

That said, I just did some research, and found a solution for this via the [ManifestMerger docs](http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger).

> tools:overrideLibrary marker

> A special marker that can only be used with uses-sdk declaration to override importing a library which minimum SDK version is more recent than that application's minimum SDK version.
Without such a marker, the manifest merger will fail. The marker will allow users to select which libraries can be imported ignoring the minimum SDK version. 

> Example, In the main android manifest : 
```xml
<uses-sdk android:targetSdkVersion="14" android:minSdkVersion="2"
              tools:overrideLibrary="com.example.lib1, com.example.lib2"/>
```

> will allow the library with the following manifest to be imported without error : 
```xml
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.example.lib1">
        <uses-sdk android:minSdkVersion="4" />
    </manifest>
```

One can just add the following to their manifest to force their SDK versions over the library:

```xml
<uses-sdk tools:overrideLibrary="com.jakewharton.rxbinding" />
```

Much nicer solution than modifying the library itself for everyone, so no worries on needing a PR from me on it now :)

Thanks anyway! Wish I'd thought to look for override mechanisms before opening the issue.

**Comment by JakeWharton** [comment]
Fair enough. If the customization becomes a problem, it's just one PR away...

**Comment by siavashabdoli** [comment]
can I override library api v 10?! 6 percent of android devices in our country have gingerbread android version. so we have to support 2.2.3. which functionality can meet problem in this case?!

**Comment by JakeWharton** [comment]
As long as you don't use bindings which reference things added after API 10
it should probably work.
