### ISSUE TITLE
Upgrading from RxBindings2 -> 3, RxView.clicks() now returns Observable<kotlin.Unit> rather than Observable<Object> in Java. This feels weird?

### ISSUE THREAD

**Issue by dphillipsprosper** [JakeWharton/RxBinding#487]
I am one of the unfortunate ones that is still writing Android apps in Java and not Kotlin. I just updated our project to AndroidX, and while doing a pass on all our dependencies to upgrade everything that supports AndroidX natively, I got to RxBinding and see that there's a 3.0.0 alpha build for AndroidX.

Cool! So I'm going through and updating all our usages from 2 -> 3. But now I got to a place where I was using RxView.clicks(). And I see that now instead of emitting an Observable stream of `Object`s as was done, it emits a `kotlin.Unit`. Which from the Kotlin side of things seems to make perfect sense. 

But it feels funny that now in my "pure" Java app I have a smattering of Kotlin types.

Is this how the Kotlin -> Java interop is supposed to be? Am I doing it wrong?

**Comment by JakeWharton** [comment]
`Unit` is an object with only one instance. `Object`, for our usage at least, was an arbitrary object we created one instance of and then used.

Does this affect you in any way? The variance should allow you to treat it as if it emitted Object.

**Comment by dphillipsprosper** [comment]
No, I guess it doesn't affect me in any way code-wise. It is causing the kotlin stdlib to be pulled in as a dependency, but a quick check of `gradle dependencies` shows that I've got a number of different dependencies (mostly yours, ha) pulling it in too. But Proguard should take care of stripping it out of release builds. So I guess in the grand scheme of things, writing `Observable<Unit>` in a few places isn't a big deal, and I should take this as the first step of converting the project to Kotlin.

Thanks for the response. I'll close this.

**Comment by maciej-kaznowski** [comment]
@dphillipsprosper  You can also do RxView.clicks(view).cast(Object.class)
