### ISSUE TITLE
@JvmField in Event classes

### ISSUE THREAD

**Issue by lkishor** [JakeWharton/RxBinding#491]
Can the fields in *Event classes be annotated with @JvmField.
This will make reading data easier for both Java & Kotlin consumers.

i.e `TextViewAfterTextChangeEvent.editable()` from 2.2.0
will become `TextViewAfterTextChangeEvent.editable`

instead of current `TextViewAfterTextChangeEvent.getEditable()`

Considering 3.0.0 is in alpha, Can/should this be done?

**Comment by liminal** [comment]
If I'm not mistaken one reason not to use @JvmField for these things is that java does not allow for field references the same way as it has method references. So as long as you have the getter instead you can do things like `myEventObservable.map(TextViewAfterTextChangeEvent::getEditable)` which is not possible if the @JvmField annotation is used.

**Comment by JakeWharton** [comment]
I agree this is unfortunate, but I don't think it's the worst thing. After all, a `get` prefix is the standard on the Java side. It's just something we'll have to live with as Java consumers (which does include me in a few places).
