### ISSUE TITLE
Rxbinding3 can't find class

### ISSUE THREAD

**Issue by tcqq** [JakeWharton/RxBinding#494]
@JakeWharton This is the code of rxbinding2, 
```
        RxTabLayout
                .selections(tab_layout)
                .observeOn(AndroidSchedulers.mainThread())
                .compose(bindUntilEvent(FragmentEvent.DESTROY_VIEW))
                .subscribe {

                }.isDisposed
```
but after upgrading to rxbinding3, `RxTabLayout`, `RxView` and other classes will report an error. What is the latest usage?

**Comment by tcqq** [comment]
`Rxbinding2` version 2.2.0 + Google 'material' library 1.1.0-alpha01 will not have problem. The latest version of the Google 'material' library is now alpha02. If upgrade to the latest version, `Rxbinding2` has an error (class not found).

**Comment by liminal** [comment]
Try replacing `RxTabLayout.selections(tab_layout)` with `tab_layout.selections()`

**Comment by JakeWharton** [comment]
What @liminal said. All of the factories are now extensions on the target type.

**Comment by tcqq** [comment]
@JakeWharton How should I use RxTabLayout in Rxbinding3 now?

**Comment by JakeWharton** [comment]
You have to use the extension function. There is no `RxTabLayout` type for Kotlin anymore. See @liminal's reply.

**Comment by tcqq** [comment]
@liminal @JakeWharton Thank you, it is fixed now.

**Comment by sjaramillo10** [comment]
Wow, I love the new integration with Kotlin extensions, but it was kind of hard for me to find the solution. It should be stated somewhere else how to transition to the rxbinding3 lib. It is easy and elegant, but not exactly self descriptive, a small comment in the Readme should be more than enough :smile:
