### ISSUE TITLE
Rxbinding3 does not work or Kotlin

### ISSUE THREAD

**Issue by Ishwor-Shrestha** [JakeWharton/RxBinding#510]
Cannot import Rxbinding3 classes in Kotlin classes. "Unresolved reference" error.

**Comment by JakeWharton** [comment]
Version 3 is only extension methods. What does your usage look like?

**Comment by jwill1517** [comment]
how to use RxView in Kotlin
RxView not found in Kotlin

**Comment by JakeWharton** [comment]
Yes, it's only extension methods.

**Comment by jwill1517** [comment]
RxView.clicks(view).throttleFirst....
how to use it in kotlin?
not found reference RxView?

**Comment by JakeWharton** [comment]
`view.clicks()`

**Comment by jwill1517** [comment]
get it !
thank u!!

**Comment by RobLewis** [comment]
Don't know if it's related, but the sample application for `RxAndroidBle` now won't compile due to a failed import `import com.jakewharton.rxbinding3.view.RxView;`. This causes an inability to resolve the symbol `RxView`. 
Gradle dependencies has this: 
`rxjava_binding        : 'com.jakewharton.rxbinding3:rxbinding:3.0.0-alpha2'`

**Comment by MuhammadjonDeveloper** [comment]
How to use in androidx

**Comment by rimonrpallan3** [comment]
```
fun View.setRxOnClickListener(function: () -> Unit): Disposable {
    return clicks()
        .throttleFirst(AppConstants.BUTTON_THROTTLE, TimeUnit.MILLISECONDS)
        .subscribe {
            function()
        }
}

fun EditText.setRxOnEditTextChangeAfter(function: (String) -> Unit): Disposable {
    return afterTextChangeEvents()
        .throttleLast(AppConstants.BUTTON_THROTTLE, TimeUnit.MILLISECONDS)
        .observeOn(AndroidSchedulers.mainThread())
        .skip(1)
        .subscribe {
            it?.let { it ->
                function(it.editable.toString())
            }
        }
}
```
This is working for me as of now.. not sure it will work after 2 months
