### ISSUE TITLE
Material design lib new bindings

### ISSUE THREAD

**Issue by rom4ek** [JakeWharton/RxBinding#511]
Latest releases [alpha05](https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha05) and [alpha04](https://github.com/material-components/material-components-android/releases/tag/1.1.0-alpha04) have quite a few new things, which could be turned into rx-bindings. (e.g. `MaterialButton` is now checkable, `TextInputLayout` has start/end clickable icons, etc.) Would you be fine with accepting PRs for these, or would you like to wait till stable 1.1.0 is out?

**Comment by JakeWharton** [comment]
We have to wait for stable
