### ISSUE TITLE
Rxbinding3   RecyclerVew how to use itemClick?

### ISSUE THREAD

**Issue by dktlu** [JakeWharton/RxBinding#512]
I want to use rxbinding3 like 

RxAdapterView.itemClicks(mListView).subscribe(new Consumer<Integer>() {
            @Override
            public void accept(Integer integer) throws Exception {
                Toast.makeText(MainActivity.this, "List Item Clicked, Position = " + integer, Toast.LENGTH_LONG).show();
            }
        });

**Comment by rusmichal** [comment]
https://github.com/JakeWharton/RxBinding/issues/494 now the factories methods are extensions

**Comment by rusmichal** [comment]
[Close]

**Comment by JakeWharton** [comment]
`mListView.itemClicks()`
