### ISSUE TITLE
Unable to import any 'rxbinding3.widgets' in kotlin file

### ISSUE THREAD

**Issue by rajputashu** [JakeWharton/RxBinding#514]
Hi Jake,
While using latest **'com.jakewharton.rxbinding3:rxbinding:3.0.0-alpha2'** library, I am unable to consume any android UI widget of your library in my kotlin file.

**For example PFB widget that I want to consume:**
RxView, RxTextView

_**PFB Screenshot for reference**_
![kotlin](https://user-images.githubusercontent.com/4385881/58469778-d0691500-815d-11e9-9bdc-1d8086bccf3d.png)
Can you please look into it.

**Comment by JakeWharton** [comment]
They are defined as extensions for Kotlin. Change your code to `view.textChanges()`.

**Comment by rajputashu** [comment]
Ok, Got it 
So they are defined as Extension Functions.
Thanks a lot! Jake

**Comment by Drjacky** [comment]
@JakeWharton 
Same problem here.
I have this: `implementation "com.jakewharton.rxbinding3:rxbinding:3.0.0-alpha2`
And this:
```
import com.jakewharton.rxbinding3.widget.*
```
But:
![image](https://user-images.githubusercontent.com/2296754/58550645-80965680-820e-11e9-9b3e-48d7b8f874b3.png)

Kotlin Version: **1.3.31**
Android Studio Version: **3.4.1**

**Comment by rajputashu** [comment]
@Drjacky 
As JakeWharton mentioned above **view.textChanges()**

> Here 'view' can be your 'EditText'

 

Therefore, your code should look like this:

> **locationEditText.textChanges()**
