### ISSUE TITLE
button.clicks() was not triggering second time.

### ISSUE THREAD

**Issue by rajputashu** [JakeWharton/RxBinding#515]
Hi Jake,
**PFB code that executes only one time**

```
compositeDisposable.add(
            searchAgentsButton.clicks()
            .subscribe {
                    startActivity(Intent(this@BookAgentActivity, SearchAgentActivity::class.java))
                })
```

On returning back from **SearchAgentActivity** to **BookAgentActivity** 

**searchAgentsButton.clicks() is not working**

in fact **_other views.clicks()_** not working as well.

Can you please let me what I am doing wrong or what could be the cause?

**Comment by JakeWharton** [comment]
Best guess is you're calling `composibleDisposable.dispose()` in `onPause()` or `onStop()` instead of `onDestroy()`. Without more information it's impossible to know, but in general it doesn't seem related to RxBinding but rather in your disposable management.

**Comment by rajputashu** [comment]
Please check the updated code...

**Comment by JakeWharton** [comment]
Seems fine, but again this doesn't seem strictly related to RxBinding but around general Rx use and subscription management. Add some doOnSubscribe and doOnDispose logging to try and figure it out what's happening.

**Comment by Steam-Ace** [comment]
> Please check the updated code...

I had the same problem
