### ISSUE TITLE
Idea - Coroutine Support

### ISSUE THREAD

**Issue by Alton09** [JakeWharton/RxBinding#545]
As coroutines are becoming more popular in Android development, have you considered offering support for them in this library? I'd imagine Flow would need to be used to implement it. This library is great by the way!

**Comment by GSala** [comment]
https://github.com/JakeWharton/RxBinding/issues/523

**Comment by JakeWharton** [comment]
Indeed. No plans. There's actually two competing libraries for this now although I forget the name of the second one.

**Comment by Alton09** [comment]
Thanks for the reference to Corbind @GSala. I'll take a look.
