### ISSUE TITLE
androidx.appcompat.widget.SearchView support

### ISSUE THREAD

**Issue by artyomefimov** [JakeWharton/RxBinding#546]
Hi!
Please suggest how can I bind androidx.appcompat.widget.SearchView instead of android.widget.SearchView. 
Seems like only the last one is supported by this lib.

**Comment by JakeWharton** [comment]
Someone will have to send a PR to add a binding for that type.

**Comment by GSala** [comment]
It seems like that type is already supported? https://github.com/JakeWharton/RxBinding/tree/master/rxbinding-appcompat/src/main/java/com/jakewharton/rxbinding4/appcompat

Are you using `implementation 'com.jakewharton.rxbinding4:rxbinding-appcompat:4.0.0'` ?

**Comment by JakeWharton** [comment]
Good spot. I didn't even bother looking.
