### ISSUE TITLE
Failed to resolve: com.jakewharton.rxbinding4:rxbinding:4.0.0

### ISSUE THREAD

**Issue by Rshalika** [JakeWharton/RxBinding#548]
Hello,
I am trying to add a dependency to library but it shows error
ERROR: Failed to resolve: com.jakewharton.rxbinding4:rxbinding:4.0.0

Is it not released yet?

**Comment by JakeWharton** [comment]
It is not. You can find all of the available releases in two places:
- Our release tab: https://github.com/JakeWharton/RxBinding/releases
- Maven central: https://search.maven.org/search?q=a:rxbinding%20%22jakewharton%22

It'll be out soon.

**Comment by JakeWharton** [comment]
You can also use the 4.0.0-SNAPSHOT although CI looks completely dead so presumably it's not publishing.
