### ISSUE TITLE
I use RxView By Kotlin  ,no find RxView   but Java  is ok.

### ISSUE THREAD

**Issue by DenisWW** [JakeWharton/RxBinding#551]
![image](https://user-images.githubusercontent.com/19258515/87520916-2f695080-c6b6-11ea-9725-2e9f918b8f7c.png)

**Comment by DenisWW** [comment]
rxbing version  4.0

**Comment by JakeWharton** [comment]
The functions are extension functions on their corresponding view type. So you'd do `theView.clicks()` now.
