### ISSUE TITLE
RxView.clicks needs tow clicks 

### ISSUE THREAD

**Issue by mlsem** [JakeWharton/RxBinding#556]
This is more like a question more than an issue.

I am using RxView.clicks with ImageButton component to handle some UI changes of some other ImageButton ( change color selector, background). and for some reason i need to perform tow clicks to make to see changes

Maybe its not a real issue but i choose to share this question.

**Comment by JakeWharton** [comment]
The `clicks` extension is just wrapping the `OnClickListener` of the view. If you need two clicks to see changes it's likely that something in the Rx stream requires it. The tests for the `clicks` extension all show that a single click is all that's needed to get an emission. Perhaps add some `doOnNext` operators with logging to figure out where the events are being lost.
