### ISSUE TITLE
Getting java.lang.IllegalStateException: Expected to be called on the main thread but was RxCachedThreadScheduler

### ISSUE THREAD

**Issue by SeethalakshmiSoman** [JakeWharton/RxBinding#560]
I am getting java.lang.IllegalStateException: Expected to be called on the main thread but was RxCachedThreadScheduler exception when I execute below code, even though its is mentioned as observeOn(AndroidSchedulers.mainThread()).

      @JvmOverloads
     fun View.setThrottledOnClickListener(throttleTime: Long = Constants.DEFAULT_DEBOUNCE, view: (View) -> Unit): Disposable {
    return RxView.clicks(this).throttleFirst(throttleTime, TimeUnit.MILLISECONDS).observeOn(AndroidSchedulers.mainThread()).subscribe({ view(this) }, {
       
        it.printStackTrace()
    }) }

This is when a custom dialog is being shown for an API response. Please help.

**Comment by JakeWharton** [comment]
Well `observeOn` only affects operators which are applied afterwards. You should pass `mainThread()` as the third argument to `throttleFirst` instead. But that's unrelated to the exception.

Sounds like you are subscribing from a background thread in which case you would need a `subscribeOn(mainThread())`.
