### ISSUE TITLE
Kotlin cannot recognize rxview, rxtextview

### ISSUE THREAD

**Issue by binZai-ComeOn** [JakeWharton/RxBinding#564]
implementation 'com.jakewharton.rxbinding4:rxbinding:4.0.0'
![image](https://user-images.githubusercontent.com/56152943/166857053-6c0d0b2f-a2bd-41ae-b88c-83a529a2f2b2.png)

**Comment by JakeWharton** [comment]
As of version 3.0, Kotlin users can use the library extensions on the view type, not static methods.

Delete the import and change your call sites to be extensions.

**Comment by binZai-ComeOn** [comment]
> As of version 3.0, Kotlin users can use the library extensions on the view type, not static methods.
> 
> Delete the import and change your call sites to be extensions.

OK, thank you for your reply
