### ISSUE TITLE
Observable textChanges() rxBinding4

### ISSUE THREAD

**Issue by reinaldoriant** [JakeWharton/RxBinding#568]
Before I use rxbinding3 can return  **io.reactivex.Observable<Boolean>** to use textChanges(), after I use rxbinding4 return from this extensions to be:
**io.reactivex.rxjava3.core.Observable<Boolean!>!**

Any suggestions to use **io.reactivex.Observable<Boolean>** for my code when using the new version from RxBinding?

**Comment by JakeWharton** [comment]
Version 4.0 uses RxJava 3. If you want RxJava 2 you need to stay on version 3.x.

**Comment by reinaldoriant** [comment]
Okay thanks
