### ISSUE TITLE
support-recyclerview module

### ISSUE THREAD

**Issue by JakeWharton** [JakeWharton/RxBinding#58]

**Comment by hzsweers** [comment]
An idea of what events could be covered (at a minimum):

* `RecyclerListener` -> `viewRecycledEvents(...)`
* `OnScrollListener` -> `scrollEvents(...)`
* `OnItemTouchListener` -> `itemTouchEvents(...)`
* `OnChildAttachStateChangeListener` -> `childAttachStateEvents(…)`

Maybes? Not sure how practical these would be

* `ChildDrawingOrderCallback`
* `ItemAnimatorFinishedListener`

**Comment by JakeWharton** [comment]
Having not used RV for anything complicated, my instinct would be that the scroll would be the most useful of these that can at least get the module off the ground. I don't know how useful the other three are having not used them for anything.

**Comment by hzsweers** [comment]
I agree.

**Comment by JakeWharton** [comment]
This is done. People can send/request new bindings as they're needed.
