### ISSUE TITLE
RxView.bindView(View view, Observable<T> source)

### ISSUE THREAD

**Issue by passsy** [JakeWharton/RxBinding#70]
When I updated to RxAndroid 1.0.0 I missed `ViewObservable.bindView(View view, Observable<T> source)`. Will it be added here? Is there another way I'm not seeing to replace this API?

https://github.com/ReactiveX/RxAndroid/blob/4bff437edfa24dde62c90d44b019b9a35855db6a/rxandroid/src/main/java/rx/android/view/ViewObservable.java

I often used a combination of this to attach observables to items in my adapters. 

```java
ViewObservable.bindView(myView, Observable.interval(500, TimeUnit.MILLISECONDS))
        .subscribe(/* do something with myView */);
```
Manually unsubscribing looks like unnecessary extra effort.

**Comment by JakeWharton** [comment]
This library is for property and event binding only. That method was an analogous to the poorly-named `bindActivity` or `bindFragment` for views which relate to the lifecycle of these objects and thus firmly outside the scope of this library.

Once view attach/detach events are added you'll be able to use this library to compose operators to a functionally-equivalent solution along the lines of:
```java
Observable.interval(500, MILLISECONDS)
    .takeUntil(RxView.attachEvents(myView).filter(e -> e.kind() == DETACH))
    .subscribe(/* do something with myView */);
```
This can easily be abstracted into a static helper method of the same signature as the `ViewObservable.bindView` method.

**Comment by passsy** [comment]
I really like the view attach/detach event solution! Are these events planned for the near future?

**Comment by JakeWharton** [comment]
Yep. They're on my list (which I should probably move to GitHub issues).

**Comment by hzsweers** [comment]
Talked with @dlew and he agreed it fits within the scope of RxLifecycle, pull request here: https://github.com/trello/RxLifecycle/pull/12

**Comment by hzsweers** [comment]
On a related note, some of the event names/usage overlap (like attach/detach). @JakeWharton @dlew any interest in maybe consolidating these in some way so users don't end up with duplicates?

**Comment by JakeWharton** [comment]
Even better!

**Comment by passsy** [comment]
API in `1.0.1-SNAPSHOT`:

```java
Observable.interval(500, MILLISECONDS)
    .takeUntil(RxView.detaches(myView))
    .subscribe(/* do something with myView */);
```
